### ISSUE TITLE
Using both System.Linq and System.Linq.Dynamic.Core 

### ISSUE THREAD

**Issue by Schaussi** [StefH/System.Linq.Dynamic.Core#106]
Hi,

is it possible to use both libraries in one .cs file?
I am using .Net Core 1.1 and VS2017.
It seems to work when I only include one library.
Using both, I get an error like "list does not contain a definition for OrderBy", e.g. when using command .OrderBy("mycol asc");
Because I also need to use the common linq expressions, it would be great to be able to use both libs.
Thank you

**Comment by StefH** [comment]
Strange.

See unit test here:
https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/test/System.Linq.Dynamic.Core.Tests/QueryableTests.OrderBy.cs#L10

Both `var orderById = qry.OrderBy("Id");` and `testList.OrderBy(x => x.Id)` are used here?

**Comment by Schaussi** [comment]
You are right. I retried again today and it worked fine without any problems.
Maybe a simple VS restart has solved this issue.
Thank you!

**Comment by StefH** [comment]
Cool !
