### ISSUE TITLE
.pdb is missing in nuget

### ISSUE THREAD

**Issue by jogibear9988** [StefH/System.Linq.Dynamic.Core#113]
1.0.7.10 and .11 is the pdb not in the nuget!

**Comment by StefH** [comment]
Yes. I when I uploaded the file to nuget I had some doubts if I uploaded the correct version.

Do you really need it ?

**Comment by jogibear9988** [comment]
For debugging it would be nice... Do you not use a CI system like Appveyor to upload to nuget?

**Comment by jogibear9988** [comment]
Appveyor can now also patch the new csproj files during build

**Comment by jogibear9988** [comment]
du you upload the ".symbol.nupkg" when you push the nuget? because it contains the pdb and the source!

**Comment by StefH** [comment]
I will upload a new NuGet with debug symbols in some time. I will write here when I've done it.

**Comment by jogibear9988** [comment]
i think with csproj you should upload both nugets, the one without pdb, and one with source and pdb
