### ISSUE TITLE
Dynamic Linq Query not usable with ORM Provider

### ISSUE THREAD

**Issue by jogibear9988** [StefH/System.Linq.Dynamic.Core#114]
I've the following linq query:

                    var qry = from a in s.Query<TagsArchiveDTO>()
                    join b in s.GetTable<TagDTO>() on a.TagId equals b.Id into tags
                    from b in tags.DefaultIfEmpty()
                    select new TagsArchiveCombinedDTO() {TagsArchive = a, Tag = b};

                var dtmi = DateTime.UtcNow.AddDays(-10);
                var dtma = DateTime.UtcNow.AddDays(10);
                var t = qry.Where(a => a.TagsArchive.ModifiedTimeStamp > dtmi && a.TagsArchive.ModifiedTimeStamp < dtma).GroupBy(b => b.Tag.Name).OrderBy(c => c.Key).Select(d => new {Name = d.Key, Count = d.Count(), Sum = d.Sum(x => x.TagsArchive.TagValue), Min = d.Min(y => y.TagsArchive.TagValue), Max = d.Max(z => z.TagsArchive.TagValue)});

but when I do the query via Dyanmic Linq

                var tx = "it.Where(it.TagsArchive.ModifiedTimeStamp > @0 && it.TagsArchive.ModifiedTimeStamp < @1).GroupBy(it.Tag.Name).OrderBy(it.Key).Select(new { it.Key as Name, it.Count() as Count, it.Sum(x => x.TagsArchive.TagValue) as Sum, it.Min(y => y.TagsArchive.TagValue) as Min, it.Max(z => z.TagsArchive.TagValue) as Max })";
                var expression = DynamicExpressionParser.ParseLambda(qry.GetType(), (Type) null, tx, dtmi, dtma);
                Delegate del = expression.Compile();
                var result = del.DynamicInvoke(qry);
                var qryT = ((IEnumerable)result).AsQueryable();

the group by will be done in memory. is it possible to fix this, so the orm mapper parses the query?

**Comment by jogibear9988** [comment]
If I use Mono 

the working expression generates following Code:

	Queryable.Select<IGrouping<string, TagsArchiveCombinedDTO>, <>f__AnonymousType1<string, int, decimal, decimal, decimal>>(Queryable.OrderBy<IGrouping<string, TagsArchiveCombinedDTO>, string>(Queryable.GroupBy<TagsArchiveCombinedDTO, string>(Queryable.Where<TagsArchiveCombinedDTO>(Queryable.SelectMany<<>f__AnonymousType0<TagsArchiveDTO, IEnumerable<TagDTO>>, TagDTO, TagsArchiveCombinedDTO>(Queryable.GroupJoin<TagsArchiveDTO, TagDTO, Guid, <>f__AnonymousType0<TagsArchiveDTO, IEnumerable<TagDTO>>>(LinqToDB.Linq.Table`1[MCC.VISU.Services.VisuServiceInterfaces.DTO.TagsArchiveDTO], LinqToDB.Linq.Table`1[MCC.VISU.Services.VisuServiceInterfaces.DTO.TagDTO], (TagsArchiveDTO a) =>
	{
		return a.TagId;
	}, (TagDTO b) =>
	{
		return b.Id;
	}, (TagsArchiveDTO a, IEnumerable<TagDTO> tags) =>
	{
		return new <>f__AnonymousType0<TagsArchiveDTO, IEnumerable<TagDTO>>(a, tags);
	}), (<>f__AnonymousType0<TagsArchiveDTO, IEnumerable<TagDTO>> <>h__TransparentIdentifier0) =>
	{
		return Enumerable.DefaultIfEmpty<TagDTO>(<>h__TransparentIdentifier0.tags);
	}, (<>f__AnonymousType0<TagsArchiveDTO, IEnumerable<TagDTO>> <>h__TransparentIdentifier0, TagDTO b) =>
	{
		return new TagsArchiveCombinedDTO()
		{
			TagsArchive = <>h__TransparentIdentifier0.a,
			Tag = b
		};
	}), (TagsArchiveCombinedDTO a) =>
	{
		return (a.TagsArchive.ModifiedTimeStamp > MCC.VISU.UnitTests.TagsTests+<>c__DisplayClass1_0.dtmi) && (a.TagsArchive.ModifiedTimeStamp < MCC.VISU.UnitTests.TagsTests+<>c__DisplayClass1_0.dtma);
	}), (TagsArchiveCombinedDTO b) =>
	{
		return b.Tag.Name;
	}), (IGrouping<string, TagsArchiveCombinedDTO> c) =>
	{
		return c.Key;
	}), (IGrouping<string, TagsArchiveCombinedDTO> d) =>
	{
		return new <>f__AnonymousType1<string, int, decimal, decimal, decimal>(d.Key, Enumerable.Count<TagsArchiveCombinedDTO>(d), Enumerable.Sum<TagsArchiveCombinedDTO>(d, (TagsArchiveCombinedDTO x) =>
		{
			return x.TagsArchive.TagValue;
		}), Enumerable.Min<TagsArchiveCombinedDTO>(d, (TagsArchiveCombinedDTO y) =>
		{
			return y.TagsArchive.TagValue;
		}), Enumerable.Max<TagsArchiveCombinedDTO>(d, (TagsArchiveCombinedDTO z) =>
		{
			return z.TagsArchive.TagValue;
		}));
	})

the Expression from dynamiclinq:


	IEnumerable<<>f__AnonymousType0<string, int, decimal, decimal, decimal>> (ExpressionQueryImpl<TagsArchiveCombinedDTO> var_$0)
	{
		return Enumerable.Select<IGrouping<string, TagsArchiveCombinedDTO>, <>f__AnonymousType0<string, int, decimal, decimal, decimal>>(Enumerable.OrderBy<IGrouping<string, TagsArchiveCombinedDTO>, string>(Enumerable.GroupBy<TagsArchiveCombinedDTO, string>(Enumerable.Where<TagsArchiveCombinedDTO>(var_$0, (TagsArchiveCombinedDTO var_$1) =>
		{
			return (var_$1.TagsArchive.ModifiedTimeStamp > 29.10.2017 15:50:57) && (var_$1.TagsArchive.ModifiedTimeStamp < 18.11.2017 15:50:57);
		}), (TagsArchiveCombinedDTO var_$2) =>
		{
			return var_$2.Tag.Name;
		}), (IGrouping<string, TagsArchiveCombinedDTO> var_$3) =>
		{
			return var_$3.Key;
		}), (IGrouping<string, TagsArchiveCombinedDTO> var_$4) =>
		{
			return new <>f__AnonymousType0<string, int, decimal, decimal, decimal>()
			{
				Name = var_$4.Key,
				Count = Enumerable.Count<TagsArchiveCombinedDTO>(var_$4),
				Sum = Enumerable.Sum<TagsArchiveCombinedDTO>(var_$4, (TagsArchiveCombinedDTO var_$5) =>
				{
					return var_$5.TagsArchive.TagValue;
				}),
				Min = Enumerable.Min<TagsArchiveCombinedDTO, decimal>(var_$4, (TagsArchiveCombinedDTO var_$6) =>
				{
					return var_$6.TagsArchive.TagValue;
				}),
				Max = Enumerable.Max<TagsArchiveCombinedDTO, decimal>(var_$4, (TagsArchiveCombinedDTO var_$7) =>
				{
					return var_$7.TagsArchive.TagValue;
				})
			};
		});
	}

**Comment by jogibear9988** [comment]
Maybe it's because we always call the Enumerable methods and not the Queryable ones?

I'll test and giva a feedback

**Comment by jogibear9988** [comment]
will you create a new nuget?

**Comment by jogibear9988** [comment]
Please reopen. After your changes the Queryable Methods are not found any more!

**Comment by jogibear9988** [comment]
There are two problems:

1.) Methods of IQueryable are static, not instance methods

**Comment by jogibear9988** [comment]
if i fix 1.) then

2.) When I use linq2db I hav e a ExpressionQueryImpl<T> and then in line 2342 of ExpressionParser

     return target.IsAssignableFrom(source);

returns false

**Comment by StefH** [comment]
OK. Create a new PR and also add some unit-tests which test this issue.

**Comment by jogibear9988** [comment]
I don't know how I could test this. I use linqdb on my system, and plot out the generated SQL

**Comment by jogibear9988** [comment]
Problem is, the "ContainsMethod(typeof(Queryable), containsSignature.Name, true, args)" does not work.
But it also does not work if you use "IEnumerable".

**Comment by jogibear9988** [comment]
fixed
