### ISSUE TITLE
Question: Extensions from MoreLinq

### ISSUE THREAD

**Issue by Franki1986** [StefH/System.Linq.Dynamic.Core#118]
Hi,

is there any chance that we can integrate some of [MoreLinq](https://github.com/morelinq/MoreLINQ) extensions?
I mean also with pull request.

**Comment by StefH** [comment]
This is possible, however the question is why would you need this?

**Comment by Franki1986** [comment]
I have two strings that contains filter expressions. 
I am accessing a database with nhibernate to linq.
Now I have a join query. One expression is for the outer table the other for the joined inner table. 
The result of the join is an anonymous type that is a tupple of outer and inner.
So if I want to access one of the results I have to extend the expression parameter with another prefix.

**Comment by Franki1986** [comment]
There are several methods like left join right join or distinctlby that are very nice to use. Like I said this is no funzional extension, it is only make the code that one ises is more readable like a left join instead of a group hoin, or more comfortable like distinctby.

**Comment by Franki1986** [comment]
I

**Comment by StefH** [comment]
Closing...
