### ISSUE TITLE
Adding LIKE operator for EF6

### ISSUE THREAD

**Issue by czielin** [StefH/System.Linq.Dynamic.Core#131]
I'm trying to figure out if there is a way to add to call a method that translates to the TSQL LIKE operator when executing against Sql Server using EF6. It looks like this was done for EF Core here:

https://github.com/StefH/System.Linq.Dynamic.Core/issues/105

I was going to take a crack at using the commit for this issue to see if I could add something myself, but I'm unable to get the solution to build. When I load it in VS 2017 the nuget dependencies refuse to load and I am presented with the following error.

Error	MSB4019	The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\WindowsXaml\v15.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.	System.Linq.Dynamic.Core	C:\Program Files\dotnet\sdk\2.0.2\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets	41	

I've tried this on two different machines. Do I need my environment set up in a particular way to load this solution?

Further, is this worth the time investment, or is there some reason this will not work like it does for EF Core?

Thanks!

**Comment by czielin** [comment]
Please disregard (for now).

Even though I couldn't build digging into the project helped me discover that it already references the proper EF6 classes, and I think I've figured out the proper syntax.

queryable.Where("parts.any(DbFunctions.Like(common.type, @0)) ", "%test");

**Comment by StefH** [comment]
Cool. Does this work for you?

**Comment by StefH** [comment]
About the solution ; you need UWP to be installed;

![uwp](https://user-images.githubusercontent.com/249938/34325271-7a620122-e88d-11e7-865f-add38027bb96.png)

**Comment by czielin** [comment]
@StefH it took me a bit to build some tests around it, but now that I have the syntax worked it all appears to be working well. Thanks!

Thanks also for the tip on UWP. I will give that a shot should I need to dive into the code again.
