### ISSUE TITLE
Possibility to parse an Expression<T, bool> to a valid expression string 

### ISSUE THREAD

**Issue by Franki1986** [StefH/System.Linq.Dynamic.Core#133]
Hello,

is it possible to parse into the other direction?
Let's say I have an expression like:

``` c#
public class Person
{
  public String Name { get; set; }
  public String FirstName { get; set; }
  public DateTime Birthday { get; set; }
}
```

`Expression<Func<Person, bool>> filterExpression= x => x.Birthday > new DateTime(2001, 1, 1);`

I would like to have something like this as result:

`"x => x.Birthday > '2007-08-31'"`

**Comment by StefH** [comment]
Just to a `.ToString()` ?

``` c#
Expression<Func<Car, bool>> filterExpression = x => x.Key > 10;
string s = filterExpression.ToString(); // "x => (x.Key > 10)"
```

**Comment by Franki1986** [comment]
Yeah, this is ok with constant variables, but if you do it with the above expression that contains a DateTime object, the result isn't the expected.
