### ISSUE TITLE
how to get related entities only one field

### ISSUE THREAD

**Issue by zqxin45** [StefH/System.Linq.Dynamic.Core#139]
in the select tests:
```cs
var test = _context.Blogs.Select("new (BlogId, Name, Posts)").ToDynamicArray();
```

it's doesn't support get related entities only one field,how to implement it
``` cs
var test = _context.Blogs.Select("new (BlogId, Name, Posts.PostId)").ToDynamicArray();
```

**Comment by StefH** [comment]
In your example : A Blog contains Posts (multiple), you cannot access `Posts.PostId`.

The example would work the other way around:

`var test = _context.Posts.First().Select("new (PostId, Title, Blog.BlogId)").ToDynamicArray();`
