### ISSUE TITLE
Question: Possible to write this using Dynamic Linq?

### ISSUE THREAD

**Issue by Elindalyne** [StefH/System.Linq.Dynamic.Core#140]
Hi there... 
I'm trying to work through something and I'm struggling a bit with how exactly to express it using Dynamic Linq...

With standard linq I can write something like this 
``` cs
var foo = new List<long>() { 1, 2, 3 };
var query = query.Where(c => c.ClientAmenities.Any(a => foo.Contains(a.AmenityID)));
```

Is it possible to express something like this with dynamic linq?

**Comment by StefH** [comment]
I did not try this, but I guess it's something like:

``` cs
var foo = new List<long>() { 1, 2, 3 };
var query = query.Where("ClientAmenities.Any(@0.Contains(a.AmenityID))", foo);
```

See also
https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/test/System.Linq.Dynamic.Core.Tests/QueryableTests.Any.cs#L90

**Comment by Elindalyne** [comment]
So I've been in the process of migrating from the kahanu/System.Linq.Dynamic package and it turns out this particular project is the one project I still had System.Linq.Dynamic referenced rather than System.Linq.Dynamic.Core... That one errors, this does not....
`query = query.Where("ClientAmenities.Any(@0.Contains(AmenityID))", foo);`

My bad...
Thanks for your help.
