### ISSUE TITLE
Question: Is there TryParseLambda

### ISSUE THREAD

**Issue by MaklaCof** [StefH/System.Linq.Dynamic.Core#141]
Hi,
I am storing entity properties (Grid columns) to database (together with width, sort, filter ...). When I get expression from database, I am trying to get actually `Entity` property, so I can get type, and other additional attributes required for application to work.  
Problem is when entity property is removed or renamed I get error : 

> 'No property or field 'PriceType' exists in type 'DbParameter''

 in code:
``` cs
var property = DynamicExpressionParser.ParseLambda(entityType, null, c); //c = PriceType which was removed.
```
I downloaded source code and search for method `TryParseLambda` which would return boolean and `LambdaExpression` as out parameter, but I couldn't found it.

How can I check if expression is valid, before calling `DynamicExpressionParser.ParseLambda`?

**Comment by StefH** [comment]
You can use a `try` `catch` construction, I think that's the only thing what you can do.
IF I had to create a `TryParseLambda` method, that would be the same I guess.

**Comment by MaklaCof** [comment]
Ok, thank you.
I was trying to avoid exceptions.
