### ISSUE TITLE
Question: GroupJoin issue

### ISSUE THREAD

**Issue by bpkinez** [StefH/System.Linq.Dynamic.Core#142]
Hi,

I'm trying to group join two collections (employees and paychecks) with join key "EmployeeId". With this method (System.Linq) everythings works fine: 

``` cs
var resultGroupJoin1 = employees.GroupJoin(paychecks, x => x.EmployeeId, y => y.EmployeeId,
(x, y) => new { x.FirstName, x.LastName, NumberOfPaychecks = y.Count() });
```

but with this method (System.Linq.Dynamic.Core):

``` cs
var resultGroupJoin2 = employees.GroupJoin(paychecks, "EmployeeId", "EmployeeId",
"new ( outer.FirstName, outer.LastName, inner.Count() as NumberOfPaychecks)");
```

I get error "The string argument ItemName cannot be empty." 

Is there any solution to this?

**Comment by StefH** [comment]
Can you try this:

``` cs
var resultGroupJoin2 = employees.AsQueryable().GroupJoin(
                paychecks,
                "it.EmployeeId",
                "EmployeeId",
"new ( outer.FirstName, outer.LastName, inner.Count() as NumberOfPaychecks)");
```

**Comment by bpkinez** [comment]
I tried your code and exactly same error ocurred.

**Comment by StefH** [comment]
See https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/test/System.Linq.Dynamic.Core.Tests/QueryableTests.GroupJoin.cs

Tests `GroupJoin_1()` and `GroupJoin_2()`.

**Comment by bpkinez** [comment]
I looked at these tests and try with this:

``` cs
var realQuery = employees.AsQueryable().GroupJoin(
    paychecks,
    employee => employee.EmployeeId,
    paycheck => paycheck.EmployeeId,
    (emp, paycheckList) => new { Name = emp.FirstName + " " + emp.LastName, NumberOfPaychecks = paycheckList.Count() });

var dynamicQuery = employees.AsQueryable().GroupJoin(
    paychecks,
    "it.EmployeeId",
    "EmployeeId",
    "new(outer.FirstName + \" \" + outer.LastName as Name, inner.Count() as NumberOfPaychecks)");
```

Real query works but dynamic doesn't. My entity classes are:

``` cs
public class Employee
{
    [Key]
    public int EmployeeId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public int Age { get; set; }

    public ICollection<Paycheck> Paychecks { get; set; } = new List<Paycheck>();
}

public class Paycheck
{
    [Key]
    public int PaycheckId { get; set; }
    public decimal HourlyWage { get; set; }
    public int HoursWorked { get; set; }
    public DateTimeOffset DateCreated { get; set; }

    [ForeignKey("EmployeeId")]
    public Employee Employee { get; set; }
    public int EmployeeId { get; set; }
}
```

**Comment by StefH** [comment]
It works fine for me, I've added example `GroupJoin_3().`

Are you sure you are using correct NuGet?

`System.Linq.Dynamic.Core`
version="1.0.8.2"

**Comment by bpkinez** [comment]
I looked at example GroupJoin_3(), it does not work again. I get same error "The string argument ItemName cannot be empty". I use correct NuGet package: 

``` cs
<PackageReference Include="System.Linq.Dynamic.Core" Version="1.0.8.2" />
```
with .NET Core 2.0 and EF Core 2.0.

**Comment by StefH** [comment]
I've created some example console-apps, see https://github.com/StefH/System.Linq.Dynamic.Core.TestApps

However these apps do not connect to real DB. Maybe that differs from your application?

**Comment by StefH** [comment]
I've also updated my example app (https://github.com/StefH/System.Linq.Dynamic.Core.TestApps/tree/master/ConsoleApp.NetCore2) to use a real DB with EF 2.01

And this works fine.

So there should be a difference?
Maybe about `[Key]` and `[ForeignKey("EmployeeId")]` ?

**Comment by bpkinez** [comment]
Hi Stef,

finally it's working now. The problem was that my paycheck list is `IQueryable<Paycheck>` type, but when I convert that list to `List<Paycheck>` type, results are yielded.

Before: 
```cs
var dynamicQuery = employees.AsQueryable().GroupJoin(
    paychecks,
    "it.EmployeeId",
    "EmployeeId",
    "new(outer.FirstName + \" \" + outer.LastName as Name, inner.Count() as NumberOfPaychecks)");
```

After: 
```cs
var dynamicQuery = employees.AsQueryable().GroupJoin(
    paychecks.ToList(),
    "it.EmployeeId",
    "EmployeeId",
    "new(outer.FirstName + \" \" + outer.LastName as Name, inner.Count() as NumberOfPaychecks)");
```

**Comment by StefH** [comment]
Ok. Closing this issue.
