### ISSUE TITLE
Question : How to orderby an attribute of a List

### ISSUE THREAD

**Issue by mhosman** [StefH/System.Linq.Dynamic.Core#143]
I have for example a class User with a list of UserTypes. In the class userType I have an attribute type:string. Now I want to order all Users by UserTypes.Type asc. How can I do this writing a query in string using System.Linq.Dynamic.Core? I'm able to search results using Any but I cant order results.

**Comment by StefH** [comment]
Not 100% the same as you ask, but this example gives some hints:
https://github.com/StefH/System.Linq.Dynamic.Core/blob/40d3b73ffadcb2a6e927767a9b9f7cdd49641663/test/System.Linq.Dynamic.Core.Tests/QueryableTests.OrderBy.cs#L28

**Comment by mhosman** [comment]
Hey @stefH thanks for your reply. You mean to order using a Select ???

**Comment by StefH** [comment]
No, ignore the `Select(...)` , that's just an example.

The statement is `Roles.OrderBy(Name)`, and the example code would be like:
``` c#
var expected = qry.SelectMany(x => x.Roles.OrderBy(y => y.Name));
var orderById = qry.SelectMany("Roles.OrderBy(Name)"));
```
