### ISSUE TITLE
Question : Performance and 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll

### ISSUE THREAD

**Issue by FransVanEk** [StefH/System.Linq.Dynamic.Core#145]
When appying an orderby  
 source.OrderBy(destinationProperty + (orderDescending ? " descending" : " ascending"));

in the debug window it shows 6 times: 

Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll

and the whole operation takes about 0.6 sec to complete.

**Comment by StefH** [comment]
Maybe related to:
https://stackoverflow.com/questions/44183208/why-is-visual-studio-telling-me-i-need-to-reference-system-private-corelib

?

**Comment by FransVanEk** [comment]
I don't think so since the error was thrown from System.Private.Corelib... so i think i have a reference to it. But if i don't what should i do to reference it in the solution. I thought system.private.corelib is the main assembly for the core framework.

**Comment by StefH** [comment]
Yes you are correct. It's a core lib.

**Comment by StefH** [comment]
closing...
