### ISSUE TITLE
Question: where should support question be posted (here or SO)

### ISSUE THREAD

**Issue by MaklaCof** [StefH/System.Linq.Dynamic.Core#146]
I just post a question on [SO](https://stackoverflow.com/questions/49190991/how-to-reference-previousordered-filtered-results-in-dynamic-linq-expression), because I am having difficulties how to dynamically create this query:
```
var rows = this.Context.Offers.Select(t => new
{
    t.Id,
    t.PartnerId,
    address = t.Partner.Addresses
        .OrderByDescending(t2 => t2.IsDefault)
        .Select(t2 => new { t2.Address.Address, t2.Address.Postcode.ZipCode })
        .FirstOrDefault()
}).ToArray();
```

I was searching where should I post my question. Some repositories requires to use GitHub issues only for bug fixes and use SO for support. Maybe adding this information to readme would be nice.

When posting to SO, I tried to found any tag that would link to this project. I couldn't find it. So, I start wonder where should support question be posted?
Can you answer me please, so I will know for future question regarding how to use this library.

I would be also very happy if my problem is solvable. So if there is a solution, please post it.

**Comment by MaklaCof** [comment]
The problem was solved. The question remains where should we post support question and if the answer is SO is there any tag for this repository?

**Comment by StefH** [comment]
SO and maybe WIKI (https://github.com/StefH/System.Linq.Dynamic.Core/wiki/Dynamic-Expressions) because issues here get closed and are invisible
