### ISSUE TITLE
Question: Making some queries dynamic possible

### ISSUE THREAD

**Issue by vasicvuk** [StefH/System.Linq.Dynamic.Core#147]
Some queries are not possible to create using Select(string) method or they are not documented how to do them. For example:
**Entity Framework Core:**
```
query.Select(x => new
            {
                Name= x.Name,
                Requests = x.Requests.Select(y => new
                {
                    Name= y.Name
                })
            });
```
**Dynamic query**
`query.Select("new (Name, Requests)")`

Is there a way to make Requests also has on selection like:

`query.Select("new (Name, Requests: new (Name)");`

**Comment by StefH** [comment]
I think this can be done like:
https://github.com/StefH/System.Linq.Dynamic.Core/blob/02fd83b24b0e8be92659aabec9f6ae45382f2ae2/test/System.Linq.Dynamic.Core.Tests/QueryableTests.Select.cs#L44

**Comment by jogibear9988** [comment]
close?

**Comment by StefH** [comment]
@vasicvuk Closing this issue now. If you still have questions, please open a new one.
