### ISSUE TITLE
Question: Using where filter it.Contains(@0) fails where it.Contains(\"keep\") works

### ISSUE THREAD

**Issue by IainmXray** [StefH/System.Linq.Dynamic.Core#148]
Hi,

Trying to create a fairly long filter expression so tried extracting the parameter in to the parameter list.  But found that the following does not work:

``` c#
List<string> testList = new List<string> {
	"something I want to filter",
	"something I want to keep"
};

var expected = testList.Where(lst => lst.Contains("keep"));
var result = testList.AsQueryable().Where("it.Contains(@0)", new List<string> { "keep"});

result.ShouldBe(expected);
```

Error "No applicable method 'Contains' exists in type 'String'"

Whereas the following does works fine:

``` c#
List<string> testList = new List<string> {
	"something I want to filter",
	"something I want to keep"
};

var expected = testList.Where(lst => lst.Contains("keep"));
var result = testList.AsQueryable().Where("it.Contains(\"keep\")");

result.ShouldBe(expected);
```

**Comment by StefH** [comment]
Hello @IainmXray ,

The code should be:
``` c#
var result = testList.AsQueryable().Where("it.Contains(@0)", "keep");
```

**Comment by StefH** [comment]
It should be

``` c#
var result = testList.AsQueryable().Where("it.Contains(@0)", "keep");
```

**Comment by jogibear9988** [comment]
close?

**Comment by IainmXray** [comment]
Sorry for the delay in replying.  Whilst this solution works for a query with one parameter it does not work for multiple parameters where you are building the set up dynamically and want to pass the params as an array.  Sorry I should have made that explicit in the query

**Comment by StefH** [comment]
Can't you just switch the code?

Like
``` c#
var result = testList.AsQueryable().Where("@0.Contains(it)", new List<string> { "a", "b" });
```

**Comment by gouhan** [comment]
![image](https://user-images.githubusercontent.com/8605053/48893368-28575400-ee7b-11e8-8588-82c637d36c7b.png)
Hi,when i take where method with contains used in generic type query，it can not work.
Just help me ,thanks.

**Comment by StefH** [comment]
@gouhan Please provide full example.

**Comment by gouhan** [comment]
@StefH ,thanks
The detail code see below:
![image](https://user-images.githubusercontent.com/8605053/48926910-e5de5780-ef0c-11e8-942e-f4c14ea4d510.png)

I find the exception reason is the "paramList" type,it's type is not explicit.
but,I need the query parameter composed by dynamically.

**Comment by StefH** [comment]
@gouhan
For my example, it works fine. See https://dotnetfiddle.net/bTkPJ2

``` c#
using System;
using System.Linq;
using System.Linq.Dynamic.Core;
					
public class Program
{
	public static void Main()
	{
		var q = new [] { new User { Id = 1, Name = "test" }, new User { Id = 2, Name = "test2" } }.AsQueryable();
		
		var parameters = new object[] { 1, "test2" }; // var parameters = new dynamic[] { 1, "test2" };  --> also works
		
		var results = q.Where<User>("Id = @0 or Name = @1", parameters);
		foreach (var result in results)
		{
			Console.WriteLine("-> " + result.Id + "_"  + result.Name);
		}
	}
}

public class User
{
	public int Id {get;set;}
	public string Name {get;set;}
}
```

**Comment by gouhan** [comment]
@StefH ，very thanks，I tried much more test with your demo code using generic type.where the unit test works fine.
I find the reason,that is the missing with builded sql,phrase is error.
![image](https://user-images.githubusercontent.com/8605053/48937426-f90f1880-ef48-11e8-9ba7-598b4f115e49.png)
(@0.Contains(1)) Or (@1.Contains(1)) I replace the 1 character with real fieldName ,it works.

**Comment by gouhan** [comment]
![image](https://user-images.githubusercontent.com/8605053/48937504-48eddf80-ef49-11e8-8bb0-9457324e7381.png)
it works

**Comment by gouhan** [comment]
@StefH ，now I have another question,help me again
![image](https://user-images.githubusercontent.com/8605053/48937779-24dece00-ef4a-11e8-92f0-380413182999.png)
First results: var results = q.Where<User>(expression);
Second : results = q.Where(o => o.Name == "test");
the two condition normally used And operation,But i want it works by OR opration.
How can i do?
if not using the linq core phrase, eg:using lambda expression，how can it works with linq core phrase together?

**Comment by StefH** [comment]
If you want an **OR** for all the 3 conditions, you need to use dynamic linq all the way.

``` c#
var results = q.Where("Name=\"test\" OR @0.Contains(1) OR @1.Contains(1)", new [] { 1, 2 });
```

**Comment by gouhan** [comment]
@StefH ,thanks.

**Comment by StefH** [comment]
Closing

**Comment by uthmanrahimi** [comment]
How can we use ColumnName.Contains(list of the array)?
I have tried the below code but did not work:


```
List<Customer> customers = new List<Customer>()
		 {
			 new Customer() { CustomerID = 1, Name = "Terri	Lee	Duffy"},
			 new Customer() { CustomerID = 2, Name = "Gail A Erickson"},
			 new Customer() { CustomerID = 3, Name = "Gigi N Matthew"},
			 new Customer() { CustomerID = 4, Name = "Michael Raheem"},
			 new Customer() { CustomerID = 5, Name = "Janice Galvin"},
			 new Customer() { CustomerID = 6, Name = "Michael Sullivan"},
			 new Customer() { CustomerID = 7, Name = "David Bradley"},
			 new Customer() { CustomerID = 8, Name = "David	Benshoof"},
			 new Customer() { CustomerID = 9, Name = "Peter	Gilbert"},
			 new Customer() { CustomerID = 10, Name = "Rebecca Bradley"},
		 };
		
		List<string> strlist = new List<string>(){"osman","ali","Janice Galvin"};
		var list = customers.AsQueryable()
			//.OrderBy("Name")
			.Where("Name.Contains(@0)", new List<string>{"osm",{"Dav"}})
			.ToList();
```
