### ISSUE TITLE
Remark: Semantic Versioning...

### ISSUE THREAD

**Issue by jogibear9988** [StefH/System.Linq.Dynamic.Core#154]
We wanted to Upgrade a Project, wich used Version 1.0.6.8, but the Update did not work, because GlobalConfig was removed!

I think you sould use Semantic Versioning, so we see if the Version has breaking Changes

**Comment by StefH** [comment]
Normally I try to use Semantic Versioning, but maybe in this case I forgot.

**Comment by jogibear9988** [comment]
Thx. Means on Breaking Changes we increase Major?

**Comment by StefH** [comment]
Major.Minor.Patch

so indeed next version would be 1.1.0

However I normally don't increase to the second digit because

**Comment by StefH** [comment]
closing....
