### ISSUE TITLE
Question: OrderByDescending availability

### ISSUE THREAD

**Issue by dyskograf** [StefH/System.Linq.Dynamic.Core#155]
Is it currently available with property name parameter?

**Comment by StefH** [comment]
Do you mean code like this:
https://github.com/StefH/System.Linq.Dynamic.Core/blob/10fc9a2ec8677f638210804c0ca636de021e6c9a/test/System.Linq.Dynamic.Core.Tests/QueryableTests.OrderByDescending.cs#L17 ?

**Comment by StefH** [comment]
@dyskograf Does this answer your question?

**Comment by StefH** [comment]
Closing, if you still have questions, please reopen this one.

**Comment by ggiacomoo** [comment]
@StefH  thanks! ;)
