### ISSUE TITLE
Question: Generic ParseLambda method

### ISSUE THREAD

**Issue by polushinmk** [StefH/System.Linq.Dynamic.Core#160]
Hi!
It will be awesome to add Generic type to ParseLambda method like in original library https://github.com/kahanu/System.Linq.Dynamic

Example:
```c#
//now
LambdaExpression lambda = DynamicExpressionParser.ParseLambda(typeof(int),typeof(bool),">10");

//in original lib
Expression<Func<int,bool>> lambdaGeneric = DynamicExpression.ParseLambda<int,bool>(">10");
```

IMO it is more convinient to use

**Comment by StefH** [comment]
In this library, you should be able to use code like this:
``` c#
Expression<Func<int>> lambdaGeneric = DynamicExpressionParser.ParseLambda<int>(null, true, ">10");
```

See https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/DynamicExpressionParser.cs#L42

**Comment by polushinmk** [comment]
Strange things but yesterday I only saw non-generic ParseLambda method and now I see generic version too.
Sorry, all works fine, this is something wrong with my eyes :)

**Comment by StefH** [comment]
It was only added in last update I think.
