### ISSUE TITLE
Issue: The option `UseDynamicObjectClassForAnonymousTypes` does not work correctly

### ISSUE THREAD

**Issue by yyjdelete** [StefH/System.Linq.Dynamic.Core#164]
When turn it on, just get an `System.ArgumentException: 'Incorrect number of arguments for constructor'`

https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/Parser/ExpressionParser.cs#L1159-L1202

The option is only used when not in `UAP10_0`, but the ctor with `KeyValuePair<string, object>[]` is only available in `UAP10_0`.

**Comment by StefH** [comment]
I'll investigate this issue.
Maybe you can write a unit-test to show this issue ?

**Comment by yyjdelete** [comment]
Do you mean #165?
This one is simple
`DynamicExpressionParser.ParseLambda(new ParsingConfig { UseDynamicObjectClassForAnonymousTypes = true }, null, "new {1 AS Id}");`

**Comment by StefH** [comment]
Option removed.
