### ISSUE TITLE
Windows 10 uwp support

### ISSUE THREAD

**Issue by fgoulet** [StefH/System.Linq.Dynamic.Core#17]
I would like to use this nice library in a Windows 10 uwp app. I was not able to compile the class DynamicClassFactory. It seems that the framework uap10.0  lacks support for the classes in System.Reflection.Emit like ModuleBuilder, TypeBuilder to create types at run-time. Any thought on this ? Thank you.

**Comment by StefH** [comment]
project.json should contain this:

```
"dotnet5.1": {
            "dependencies": {
                "System.Collections": "4.0.10",
                "System.Collections.Concurrent": "4.0.10",
                "System.Dynamic.Runtime": "4.0.0",
                "System.Reflection.Emit": "4.0.0",
                "System.Reflection.TypeExtensions": "4.0.0",
                "System.Linq.Expressions": "4.0.10",
                "System.Linq.Queryable": "4.0.0"
            }
        },
```

However, one thing which will not yet work is AppDomain to load assemblies. I need to refactor that completely to use IOC on that code.

See latest code from this project which contains an example UAP app.

If this version is fine, I can also create a NuGet version 1.0.1

**Comment by fgoulet** [comment]
Yes, an updated NuGet package would be nice.
Thank you.

**Comment by StefH** [comment]
Version 1.0.1 has been pushed to NuGet, please test.

**Comment by fgoulet** [comment]
I tested with EFCore and everythings seem to work great.
Thanks!

**Comment by StefH** [comment]
OK, can you also test the new 1.0.2 NuGet ?
https://www.nuget.org/packages/System.Linq.Dynamic.Core/1.0.2

**Comment by fgoulet** [comment]
1.0.2. works fine for me too.

**Comment by StefH** [comment]
Thanks. I will close issue.
