### ISSUE TITLE
File version attribute is 0.0.0.0

### ISSUE THREAD

**Issue by hypetsch** [StefH/System.Linq.Dynamic.Core#171]
The file version attribute of "System.Linq.Dynamic.Core.dll" is 0.0.0.0. I think it would be good the have the actual version set there:

![image](https://user-images.githubusercontent.com/16302578/41029162-476aa69c-697b-11e8-8c4f-18d7b1565ce1.png)

**Comment by StefH** [comment]
Latest version looks correct:
![image](https://user-images.githubusercontent.com/249938/59624879-3a128880-9138-11e9-8af2-b9cdb721539b.png)
