### ISSUE TITLE
Issue: DynamicQueryableExtensions.OrderBy extension method not using ParsingConfig parameter

### ISSUE THREAD

**Issue by mhubis** [StefH/System.Linq.Dynamic.Core#172]
This method is not passing the ParsingConfig parameter to the OrderBy method. This is causing the default ParsingConfig to be used by the ExpressionParser. The issue exists in DynamicQueryableExtensions.cs at line 960.

**Comment by StefH** [comment]
Solved, please use new NuGet

**Comment by mhubis** [comment]
Thanks!
