### ISSUE TITLE
Error when trying to access an object declared on another lambda

### ISSUE THREAD

**Issue by VAdri** [StefH/System.Linq.Dynamic.Core#173]
Trying to parse a dynamic linq expression with multiple lambdas, when accessing an object declared on a parent lambda, throws an error:

```C#
context.Companies.Where("Employees.Any(e => e.Salary < it.MinimumSalary)");
```
```
System.Linq.Dynamic.Core.Exceptions.ParseException : No property or field 'MinimumSalary' exists in type 'Employee'
```

The parser ignores the identifiers (`e` and `it`) and uses automatically the last lambda that was declared, which leads to an error when trying to access the `Company` object inside the `Employee` lambda.

However, this behavior works as expected on a regular linq expression:

```C#
context.Companies.Where(c => c.Employees.Any(e => e.Salary < c.MinimumSalary));
```

**Comment by StefH** [comment]
The code will not work at all?

You should use something like:
``` c#
context.Companies.Where("Employees.Any(Salary < 1000)");
// or
context.Companies.Where("Employees.Any(Salary < @0)", 1000);
```

See also https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/test/System.Linq.Dynamic.Core.Tests/QueryableTests.Any.cs#L36

**Comment by StefH** [comment]
Closing. If you still have an issue. Comment here or open new.
