### ISSUE TITLE
Including more methods from System.Math?

### ISSUE THREAD

**Issue by fredrikkronander** [StefH/System.Linq.Dynamic.Core#174]
Hi,

Would it be possible to add more methods from System.Math, for example Math,Round() and similar? (right now you can only use the constants). It would help a lot in my current project where I use dynamic expressions to query data, and handling such math operations outside the expressions will be tricky there.

Regards
Fredrik

**Comment by StefH** [comment]
Hello @fredrikkronander

This seems to work fine already ?
``` c#
public class TestObject
{
	public int X { get; set; }
	public double D { get; set; }
	public string Name { get; set; }
}

void Main()
{
	var q = new[] { new TestObject { D = 4.6 }, new TestObject { D = 2 } }.AsQueryable();
	var result1 = q.Select(x => Math.Round(x.D));
	result1.Dump(); // Dump using Linqpad
	var result2 = q.Select("Math.Round(it.D)");
	result2.Dump(); // Dump using Linqpad
}
```

LinqPad:
![image](https://user-images.githubusercontent.com/249938/48062054-2b86ea80-e1c1-11e8-894e-314442077f68.png)

**Comment by StefH** [comment]
@fredrikkronander

I'm closing this issue now. If you still have questions, reply here or open new issue.

**Comment by fredrikkronander** [comment]
Thanks for your help Stef, really appreciated!


Fredrik Kronander
Solution Architect

 [cid:image001.gif@01D3B552.9AA9A070]

Mobile: +46 (0)70 794 19 20, Office: +46 (0)8 692 91 00
Sveavägen 13, 10 tr, 111 57 Stockholm, Sweden
www.brilliantfuture.se<applewebdata://B5F5046F-C313-4BBA-8ED4-67CCD95154D1/brilliantfuture.se>     linkedIn<applewebdata://B5F5046F-C313-4BBA-8ED4-67CCD95154D1/linkedIn.se>

Vill du veta mer om hur vi behandlar dina personuppgifter? Klicka här<https://www.brilliantfuture.se/om-oss/gdpr/>.




________________________________
Från: Stef Heyenrath <notifications@github.com>
Skickat: Wednesday, January 2, 2019 9:10:48 PM
Till: StefH/System.Linq.Dynamic.Core
Kopia: Fredrik Kronander; Mention
Ämne: Re: [StefH/System.Linq.Dynamic.Core] Including more methods from System.Math? (#174)


@fredrikkronander<https://github.com/fredrikkronander>

I'm closing this issue now. If you still have questions, reply here or open new issue.
