### ISSUE TITLE
Some extension methods to write Rule Engine using Dynamic Expressions.

### ISSUE THREAD

**Issue by mukeshrebari** [StefH/System.Linq.Dynamic.Core#175]
Hi Everyone,
   I was just trying to come up with some kind of rule engine for the customer-specific requirements in SaaS Model. So I wrote some extension methods around this Library. Can you guys suggest me if, I am doing this in right way or not?

[dynamic_expression.cs](https://gist.github.com/indiaweblab/1a478a059c4bedd8571c8774ca11225a)

**Comment by StefH** [comment]
Can you explain more how you would use this?

**Comment by mukeshrebari** [comment]
I apologies for delayed response. What I would do is i'll create an Example Project this weekend for Usages of Extension Methods(so called Rule Engine :)). We are already using it heavily in one of our ERP Project.

Above link is broken and here is updated gist with new link [dynamic_expression.cs](https://gist.github.com/mukeshrebari/1a478a059c4bedd8571c8774ca11225a)

**Comment by StefH** [comment]
@mukeshrebari any update on this, or can this issue be closed?

**Comment by mukeshrebari** [comment]
Hi Stef Heyenrath, I know it took so long to reply but finally i have prepared demo project to showcase how we are using your wonderful  library.
here is the link of [DemoProject](https://github.com/OneSoniTech/DynamicRulesDemo)

**Comment by StefH** [comment]
@mukeshrebari I've created a PullRequest on your example project which uses this project (System.Linq.Dynamic.Core) instead of the custom `DynamicLinq.cs` file.

I'm closing this issue now because your project is a custom extension which can be useful, but it's not really related to the common or core functionality from this project.
