### ISSUE TITLE
No generic method 'Contains' on type 'System.Linq.Enumerable

### ISSUE THREAD

**Issue by fabich** [StefH/System.Linq.Dynamic.Core#178]
Hi

I have the following issue:
```C#
System.InvalidOperationException: 'No generic method 'Contains' on type 'System.Linq.Enumerable' is compatible with the supplied type arguments and arguments. No type arguments should be provided if the method is non-generic. '
```

The code that I'm trying to run:
```C#
var s = = "@0.Contains(it.FkGenerickey)";
var list = new List<string> {"2736", "1903"};
var expression = DynamicExpressionParser.ParseLambda<TDTO, bool>(null, false, s, list)
```

I saw in other issues that the following code runs without any issues:
```C#
var result = testList.AsQueryable().Where("@0.Contains(it)", new List<string> { "a", "b" });
```

What am I missing?

**Comment by fabich** [comment]
wrong type of list.
list needed to be List<int>

**Comment by oneillci** [comment]
I'm having this exact same issue using both approaches:
```cs
var predicate = "@0.Contains(instrumentId)";
var list = new List<int> { 1, 2 };
var expression = DynamicExpressionParser.ParseLambda<T, bool>(null, false, predicate, list);` // errors here
queryable = querable.Where(expression);
```

or
```cs
queryable = queryable.Where("@0.Contains(instrumentId)", new List<int> { 1, 2 });
```

Can you see anything I'm doing wrong?

Message: "No generic method 'Contains' on type 'System.Linq.Enumerable' is compatible with the supplied type arguments and arguments. No type arguments should be provided if the method is non-generic. "
    Source: "System.Core"
    StackTrace: "   at System.Linq.Expressions.Expression.FindMethod(Type type, String methodName, Type[] typeArgs, Expression[] args, BindingFlags flags)\r\n   at System.Linq.Expressions.Expression.Call(Type type, String methodName, Type[] typeArguments, Expression[] arguments)\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseEnumerable(Expression instance, Type elementType, String methodName, Int32 errorPos, Type type) in C:\\Users\\azurestef\\Documents\\Github\\zzzprojects\\System.Linq.Dynamic.Core\\src\\System.Linq.Dynamic.Core\\Parser\\ExpressionParser.cs:line 1854

**Comment by oneillci** [comment]
Looked at this for a few hours and solved it minutes after posting the above - typical 😆 

My issue is that my underlying type is a nullable int, so changing my list to this fixed it :)
```cs
var list = new List<int?> { 1, 2 };
```
