### ISSUE TITLE
Feature: Implement SourceLink

### ISSUE THREAD

**Issue by StefH** [StefH/System.Linq.Dynamic.Core#179]
SourceLink can be added, so users can debug their own stores much more easy. More info on https://github.com/dotnet/sourcelink

**Comment by StefH** [comment]
csproj
``` xml
<PublishRepositoryUrl>true</PublishRepositoryUrl>
<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
```

**Comment by zspitz** [comment]
Source Link appears to be broken ATM.

The [current instructions to enable Source Link](https://github.com/dotnet/sourcelink#using-source-link-in-net-projects) require a `PackageReference` for the appropriate source code provider (for Dynamic LINQ this would be GitHub):

```xml
<PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All"/>
```

But none of the Dynamic LINQ projects have this reference. 

I've found [Nuget Package Explorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer) useful for debugging this issue.

(ping @JonathanMagnan)
