### ISSUE TITLE
GroupBy fails for field named SHORT

### ISSUE THREAD

**Issue by alexfestbaum** [StefH/System.Linq.Dynamic.Core#180]
Issuing a GroupBy against a entity field named SHORT results in the following error:

'.' or '(' or string literal expected

`var result = baseData
                .Select(entityName)
                .GroupBy("SHORT", "it")
                .Select("new (it.Key as value, it.Count() as count)")
                .ToDynamicList();
`

Short seems to be a protected key/word. How can I resolve this issue? Padding the field with '[SHORT]' like SQL Server would do did not help.

**Comment by StefH** [comment]
`SHORT` is *probably* a reserved keyword.
