### ISSUE TITLE
Question: Issue with DateTime Field

### ISSUE THREAD

**Issue by dixitsuneel** [StefH/System.Linq.Dynamic.Core#183]
If the model contains a DateTime field
```c#
class Entity {
   public DateTime DateLastModified { get;set; }
}
```

If I apply a filter using `queryable.Where("DateLastModified > '2018-07-17'")` then with Ef Core 2.1 I am seeing that the query is translated to

``` sql
where DateLastModified>'2018-07-17T00:00:00.0000000'
```
This leads to the sql query being failed. 

It wasn't an issue with Ef Core 2.0 but I am seeing this issue with Ef Core 2.1.1

**Comment by StefH** [comment]
Hello @dixitsuneel.

I did test this with EF 2.1.1 with real database en with in-memory database, and in both cases all works.

Note that you need `\"` instead `'`.

Example:
``` C#
var carDateLastModified = context.Cars.Where(config, "DateLastModified > \"2018-01-16\"");
```

**Comment by StefH** [comment]
@dixitsuneel Closing this issue, if you still have problems, comment here of create a new issue.
