### ISSUE TITLE
Add custom static classes for parsing

### ISSUE THREAD

**Issue by OlegNadymov** [StefH/System.Linq.Dynamic.Core#187]
Hi!
Could you create a convenient way of adding my custom static classes which I can use for dynamic parsing?
I've used for System.Dynamic.Linq this way [https://stackoverflow.com/a/18313782](https://stackoverflow.com/a/18313782). It uses Reflection. So it's not convenient.
I hope you can explain me how can I do it in System.Linq.Dynamic.Core.

Thank you in advance!

**Comment by StefH** [comment]
Did you try this solution ?
https://stackoverflow.com/questions/18313362/call-function-in-dynamic-linq/18313782#18313782

Or else I should make this method public:
https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/Parser/PredefinedTypesHelper.cs#L70

**Comment by OlegNadymov** [comment]
Yes, I did. I had tried this solution and wrote about it in my message. The solution is based on Reflection. It's not convenient.

Could you make the method with the signature is like below:
public static void TryAdd(Type type, int x)
And what is parameter "x" mean here?

Or if you don't mind I can fork your project and create pull request.
What do you think?

**Comment by OlegNadymov** [comment]
It's a quite good solution. But I have to add reference to `System.Linq.Dynamic.Core` in all projects in which I have classes for dynamic parsing from. Also I need to decorate the classes with `DynamicLinqTypeAttirubute`. I can do it for my case. But if I have an external project I won't can do it.

**Comment by StefH** [comment]
You can also extend the https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/CustomTypeProviders/DefaultDynamicLinqCustomTypeProvider.cs and add your types to the list there, see for example here : https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src-console/ConsoleAppEF2.1.1/Program.cs#L22

**Comment by OlegNadymov** [comment]
Yes! It meets my needs! Thank you!

**Comment by OlegNadymov** [comment]
Yes! It meets my needs! Thank you!
