### ISSUE TITLE
Implicitly conversion from a non-nullable value type to the nullable form of that value type is broken?

### ISSUE THREAD

**Issue by yyjdelete** [StefH/System.Linq.Dynamic.Core#188]
See https://github.com/StefH/System.Linq.Dynamic.Core/wiki/Dynamic-Expressions#conversions
Or I misused this in an not proper way?

Hit this issue with debug an query issue with efcore when eval at local, and it's able to write an reproduct case without efcore. Tested with `1.0.8.11`

```cs
        public class ConsumptionWithDateLite
        {
            public DayOfWeek? DayOfWeek { get; set; }
        }

                var a1 = Enumerable.Repeat(0, 100)
                    .Select((d, i) => new DateTime(2000, 1, 1).AddDays(i))
                    .AsQueryable()
                    //.Select("new (DayOfWeek)")
                    .Select<ConsumptionWithDateLite>("new (DayOfWeek)");

                var z1 = a1.ToList();
                System.Diagnostics.Debug.Assert(!z1.Any(zx => zx.DayOfWeek == null));
```

Update: This get null on netcoreapp, and an `System.Security.VerificationException:“操作可能会破坏运行时稳定性。”`(`Operation may break runtime stability`) on netfx

**Comment by StefH** [comment]
Can you please post a full project example for dotnet core / normal .net ?

**Comment by yyjdelete** [comment]
@StefH 
https://github.com/yyjdelete/DynamicLinqTestCast
`dotnet run -f net45` or `dotnet run -f netcoreapp2.1`, or you can retarget to other installed TargetFrameworks.

**Comment by StefH** [comment]
Thanks.

I'm able to reproduce and I've fixed it. Now I need to add some unit-tests.

You can already take a look here:
https://github.com/StefH/DynamicLinqTestCast/tree/test_issue_188
+
https://github.com/StefH/System.Linq.Dynamic.Core/tree/issue_188

**Comment by yyjdelete** [comment]
👍

**Comment by StefH** [comment]
I'll create a new NuGet in some time.
