### ISSUE TITLE
NotEqual filter not working with DateTime

### ISSUE THREAD

**Issue by Muchiachio** [StefH/System.Linq.Dynamic.Core#19]
```C#
public class Program
{
    public static void Main(string[] args)
    {
        IQueryable<Model> models = new[] { new Model() }.AsQueryable();

        Console.WriteLine(models.Where("Date != null").ToArray().Length);
    }
}

public class Model
{
    public DateTime Date { get; set; }
}
```

Throws `The binary operator NotEqual is not defined for the types 'System.DateTime' and 'System.String'`. This works in `System.Linq.Dynamic` and `System.Linq`.

**Comment by StefH** [comment]
Issue is solved, some unit-tests are also added.

Can you please verify this library ? Or do you want a NuGet to test ?

**Comment by Muchiachio** [comment]
I confirmed, it's working.
