### ISSUE TITLE
Question: Not applicable aggregate method 'Any' exists

### ISSUE THREAD

**Issue by thanhnntq** [StefH/System.Linq.Dynamic.Core#196]
Error when using
``` c#
AList.Where("AListField.Any(__tx => __tx.ASubField == 1) || AListField.Any(__tx => __tx.ASubField == 2)")
```

**Comment by StefH** [comment]
As a workaround, use `Contains`:

``` c#
var anyTest = new []
{
    new { id = "1", values =new [] { 1, 2, 3 } },
    new { id = "2", values =new [] { 1, 4 } },
    new { id = "3", values =new [] { 9, 5 } }
}.AsQueryable();

var any1 = anyTest.Where(x => x.values.Contains(1));
Console.WriteLine("any1 {0}", JsonConvert.SerializeObject(any1, Formatting.Indented));

var any2 = anyTest.Where("values.Contains(1)");
Console.WriteLine("any2 {0}", JsonConvert.SerializeObject(any2, Formatting.Indented));
```

**Comment by thanhnntq** [comment]
I was change it to:
AList.Where(ASubList.Select(__tx => __tx.ASubFile).Contains(3) && ASubList.Select(__tx => __tx.ASubFile).Contains(4))
Then i have an error:
InvalidOperationException: No generic method 'Contains' on type 'System.Linq.Enumerable' is compatible with the supplied type arguments and arguments. No type arguments should be provided if the method is non-generic.

**Comment by thanhnntq** [comment]
In normal Linq it work very nice. But in Dynamic Linq it got an error!
If i using only one "AListField.Any(__tx => __tx.ASubField == 1)" then nothing error. But if i have two expression with or operation or and operation i got an error!

**Comment by thanhnntq** [comment]
I was debug in System.Linq.Dynamic.Core source i found:
When parse first expression "AListField.Any(__tx => __tx.ASubField == 1)" it create an expression like this "Param1$.ASubField == 1" with method name = "Any" but when parse second expression it was create an expression like this: "Param0$ => Param1$.ASubField == 2"
and here it can't find method for this expression and i got an error.

**Comment by thanhnntq** [comment]
Here is an example:
`public class TestAnyClass
        {
            public string name { get; set; }
            public ICollection<ChildClass> childs { get; set; }
        }

        public class ChildClass
        {
            public string childName { get; set; }
        }

        [Fact]
        public void Where_Dynamic_Any_Equals()
        {
            var testList = new List<TestAnyClass>();
            var qry = testList.AsQueryable();
            var rs = qry.Where("childs.Any(__tx => __tx.childName == \"Hi\")");
            var rs2 = qry.Where("(childs.Any(__tx => __tx.childName == \"Hi\")) || (childs.Any(__tx => __tx.childName == \"Hello\"))");
        }`
And error in rs2: 
![image](https://user-images.githubusercontent.com/30698814/44101898-a402472a-a012-11e8-9a8c-8c2a0baafb45.png)

**Comment by thanhnntq** [comment]
Expression 1: 
![image](https://user-images.githubusercontent.com/30698814/44102874-eeb38bf6-a014-11e8-89c4-17dbbb97422e.png)
Expression 2:
![image](https://user-images.githubusercontent.com/30698814/44102896-fb62fbca-a014-11e8-964c-d4582b5715af.png)
And error:
![image](https://user-images.githubusercontent.com/30698814/44102919-127aa5f6-a015-11e8-8f4e-71d666696cf2.png)

**Comment by StefH** [comment]
Sorry, the `Any` method is not _(yet)_ supported. As a workaround, use `Contains`.
