### ISSUE TITLE
Can't install using nuget in Asp.Net 4.0 Web Pages project

### ISSUE THREAD

**Issue by jesusmogollon** [StefH/System.Linq.Dynamic.Core#20]
Thanks for keeping this project alive.

I'm using visual studio 2010, my project is in Asp.Net Web Pages  .Net 4.0
When using Nuget 2.8.60318.667 to install the package, Iget the following error:

'System.Linq.Dynamic.Core' already has a dependency defined for 'System.Collections.Concurrent'.

I tried to install the package NetLegacySupport.ConcurrentDictionary 1.1.0 and did it again but got the same error.

Any clues?

**Comment by Vlandmist** [comment]
I'm using VS2013 and solved updating nuget package manager to last version

**Comment by StefH** [comment]
This issue looks at bit like :
https://github.com/NuGet/Home/issues/2825

**Comment by jesusmogollon** [comment]
Looks like it is the issue, we just wait for the new nuget version?

**Comment by StefH** [comment]
As a workaround you can just download the nuget package from nuget.org and extract the library (dll) which you need for your framework.

Or upgrade VS to the latest 2015 is thats possible.

**Comment by jesusmogollon** [comment]
I have upgraded to visual studio 2013 and I can install it and build, but my project is not MVC and is 4.0 when I try to execute the page it raises a load exception when I look at it it is asking to load the System.Web.MVC 1.0.0, if I uninstall the dynamic library the project runs fine.

This library works only on MVC?

**Comment by StefH** [comment]
This library does not have a dependency on MVC.

Can you please share your project or provide more details?

**Comment by StefH** [comment]
Any update?

**Comment by jesusmogollon** [comment]
Sorry for the late response.

I ended up not using this library, it keep asking for the MVC reference, I figured it must be something related to nuget and the framework 4.0

I was using visual studio 2013.
