### ISSUE TITLE
How to query complex entities

### ISSUE THREAD

**Issue by SpeakHero** [StefH/System.Linq.Dynamic.Core#203]
```c#
public role {
  public string id{get;set;}
  public string name{get;set;}
}

public roleClaims{
  public string id{get;set;}
  public string roleid{get;set;}
  public role  role{get;set;}
}
```
How to  select ?
I need to choose. role.name
I do it like this:
`Context.Set<roleClaims>().Select("new{ id, roel.name}")`   but  this is error！
What should I do?

**Comment by StefH** [comment]
This should work?

`Context.Set<roleClaims>().Select("new{ id, role.name}")`

Can you post the error message?

**Comment by os1r1s110** [comment]
Maybe it's just the typo in the code? If it was copy pasted, then the only error might be the typo in the `role.name` as mentioned by StefH
> `Context.Set<roleClaims>().Select("new{ id, roel.name}")`

**Comment by StefH** [comment]
Closing...

If you still have issues, comment here or open a new issue.
