### ISSUE TITLE
Documentation of supported operations

### ISSUE THREAD

**Issue by Enngage** [StefH/System.Linq.Dynamic.Core#205]
Thanks for this awesome library, I don't know what I would do without it. 

I have request regarding documentation and supported parameters. I'm using this with EF and I had a need to create a order by `Len` query. I didn't see any obvious ways to do that and using:

`query.OrderBy($"Len({FieldName}) DESC");`

Does not work because no `Len` method exists in given type. However, using

`query.OrderBy($"{FieldName}.Length DESC");`

Works perfectly fine and generates correct SQL query. This was pretty much lucky guess as I didn't even know if its supported. Am I missing something obvious in documentation or in my understanding? 

Thanks!

**Comment by StefH** [comment]
The documentation is not always very clear, I still need to make time for that.

However, normally methods calls which are present on object in C# .NET can be used in dynamic queries.

See also https://github.com/StefH/System.Linq.Dynamic.Core/issues/54
