### ISSUE TITLE
Issue: new() expression cannot handle complex types

### ISSUE THREAD

**Issue by david-garcia-garcia** [StefH/System.Linq.Dynamic.Core#206]
Currently, the new() expression can be used to instantiate know types, such as:

`query = query.select("new MyNamespace.MyClass(value1 as prop1, value2 as prop2)");`

ExpressionParser.cs is not able to properly handle complex types, such as generics or classes nested inside other classes, i.e.

`query = query.select("new MyNamespace.MyClass+MySubClass(value1 as prop1, value2 as prop2)");`

The parser is properly extracting the full namespace and class name, it just fails to properly detect the type in it's FindType() method. I really don't understand why the implementation of such a method is so convoluted, but following the current philosophy of the method, this is the patch that will allow new() to parse nested class names:

![image](https://user-images.githubusercontent.com/9599352/47002725-0953fc80-d12e-11e8-8aab-92f01c4b5e62.png)

To properly support generics though some extra work needs to be done, as it will only consider dot and plus as valid tokens in a class name:

`while (_textParser.CurrentToken.Id == TokenId.Dot || _textParser.CurrentToken.Id == TokenId.Plus)`

**Comment by david-garcia-garcia** [comment]
Will be proposing a PR when I find some time, just posting here for the record.

**Comment by StefH** [comment]
Thanks for the PR.

Can you also add a new unit-test to test this specific issue?

**Comment by StefH** [comment]
Tests fail; related to the test DTO classes, these should be normal classes, not nested in a test class.

**Comment by StefH** [comment]
NuGet 1.0.9 is added.
