### ISSUE TITLE
Question: why is Distinct not supported?

### ISSUE THREAD

**Issue by Vlandmist** [StefH/System.Linq.Dynamic.Core#21]
**Distinct()** method is not supported, not in the original @NArnott project (now disappeared.. why?) and not in this fork. what's the reason behind it? is it too difficult to implement?

**Comment by StefH** [comment]
I'll copy the logic from https://github.com/kahanu/System.Linq.Dynamic/blob/master/Src/System.Linq.Dynamic/DynamicLinq.cs#L129

**Comment by Vlandmist** [comment]
ok! that's great, I'll try it asap

**Comment by StefH** [comment]
Code + tests have been added to Github.

Please take a look.
If you want a new NuGet, I can create this if needed.

**Comment by Vlandmist** [comment]
thank you, yes a new nuget would be great to test it

**Comment by StefH** [comment]
https://www.nuget.org/packages/System.Linq.Dynamic.Core/1.0.3.1

**Comment by StefH** [comment]
Are you able to verify ?

**Comment by Vlandmist** [comment]
I tried but I'm having problems, how can I retrieve a distinct list of Persons by name? (like the commented line). This is my code

```
            var lp = new List<Person>();
            lp.Add(new Person {Name = "John", Surname = "Lennon"});
            lp.Add(new Person {Name = "John", Surname = "Williams"});
            lp.Add(new Person {Name = "Paul", Surname = "MC"});
            lp.Add(new Person {Name = "Paul", Surname = "Allen"});
            lp.Add(new Person {Name = "Ringo", Surname = "Starr"});
            

             var qp = lp.AsQueryable().Select("(Name).Distinct");
            //var qp = lp.AsQueryable().Select(p => p.Name).Distinct();

            foreach (var n in qp)
            {
                Console.WriteLine(n.ToString());
            }

            Console.ReadKey();
```

gives a **ParseException** 

```
An unhandled exception of type 'System.Linq.Dynamic.Core.Exceptions.ParseException' occurred in System.Linq.Dynamic.Core.dll
Additional information: No property or field 'Distinct' exists in type 'String'
```

**Comment by StefH** [comment]
I think the method you are looking for is like:
`var qp = lp.AsQueryable().Distinct("Name");`

However that method does not exists (yet). I'll take a look if I can add this one.

**Comment by Vlandmist** [comment]
Yes, your sample works, but I couldn't think of a dynamic use for it since Distinct is explicit. Also I can't seem to use Distinct inside a Where.("...") expression.

I'm working on a Linq to Entities (SQL Server) project using the original @NArnott library and some complex queries aren't easy to manage without support for **Distinct** and  **GroupBy** methods.

**Comment by StefH** [comment]
Can you provide an example for the ***Where*** statement ?

Because ***Select*** is supported : `var result = queryable.Select("abc.Distinct()");`

**Comment by Vlandmist** [comment]
I'll answer with a sample asap. what is "abc" in your code sample?

**Comment by StefH** [comment]
A property from a user which is a list or iqueryable or ienumerable.

**Comment by StefH** [comment]
Any luck?

**Comment by Vlandmist** [comment]
Sorry mate, didn't have time to check it in these days. I'll write here when I have a couple more samples. keep on the good work

**Comment by StefH** [comment]
Can you provide feedback ?

**Comment by Vlandmist** [comment]
Ok let's forget about Distinct() support in Where. My situation was an extreme case and it's not worth replicating.

About **Distinct in select** I can't seem to make it work for simple lists (not nested object like your code sample)

This is my code:

            var integerList = new List<int>();
            integerList.AddRange(new []{1,1,2,3,4,4,5});
            
            //This works
            var xx = integerList.AsQueryable().Select("it").Distinct();

            //exception
            //Additional information: No property or field 'Distinct' exists in type 'Int32'
            var xy = integerList.AsQueryable().Select("it.Distinct()");`

            //exception
            //Additional information: No property or field 'Distinct' exists in type 'Int32'
            var xyz = integerList.AsQueryable().Select("Distinct(it)");


Maybe it's me that is not undertanding how this works. is there any way to achieve what I'm trying to do? if not, and if it's not useful to implement it, we can close this issue.

**Comment by StefH** [comment]
Distinct does not solve your problem I think:

In your original question:
```c#
// real linq
var qp = lp.AsQueryable().Select(p => p.Name).Distinct();

// dynamic linq
var qpDynamic = lp.AsQueryable().Select("Name").Distinct();
```


The value from **qp** will be a _List of Strings_ with the values : "John", "Paul" and "Ringo".

What you are trying do does not make sense I think, I have a feeling you want to use a groupby logic.
<br>
Note that real linq code like 
```c#
var error = lp.AsQueryable().Select(p => p.Name.Distinct());
```
does also not compile.

**Comment by Vlandmist** [comment]
Ok, thanks, that makes perfect sense, I'll close the issue.
