### ISSUE TITLE
DynamicExpression accessibility

### ISSUE THREAD

**Issue by rpaschoal** [StefH/System.Linq.Dynamic.Core#22]
Hello,

First of all, thank you for all your effort porting this project to .NET Core.

Is there any chance you could make DynamicExpression class public? The reason for that is because I use "ParseLambda" method to generate dynamic filters in an application by using PredicateBuilders.

Many Thanks.

**Comment by StefH** [comment]
- fixed
- updated online doc
- published new new nuget to https://www.nuget.org/packages/System.Linq.Dynamic.Core/1.0.3.2

please verify

**Comment by rpaschoal** [comment]
Hello @StefH,

Thanks for the quick reply and change to the API.

I can see the signature is a little bit different. This is how I use on the original Linq.Dynamic:

System.Linq.Dynamic.DynamicExpression.ParseLambda<Entity, bool>(expression, null)

Where "Entity" is the type of the code-first entity and "expression" is a string with many linq expressions.

Following your API, would this produce the same output?

System.Linq.Dynamic.Core.DynamicExpression.ParseLambda(false, typeof(Entity), typeof(bool), expression, null)

Oh, by the way, after calling that I had to parse a LinqExpression to an Expression using this:

var typedExpression1 = (Expression<Func<Entity, bool>>) Expression.Lambda(expression1, null);

Now it compiles, not sure if it works yet. Need to test it. 

Thanks!

**Comment by StefH** [comment]
Correct, I changed the interface and the internal business logic a bit.

When calling the new API, just use
`DynamicExpression.ParseLambda(false, typeof(Entity), null, expression)`

See https://system-linq-dynamic-core.azurewebsites.net/html/938537c7-8fa2-b300-1f27-5aadcd5440e5.htm for details:

**Comment by rpaschoal** [comment]
Thanks Mate,

I have simplified my call.

Cheers :+1:

**Comment by StefH** [comment]
Note that in the latest version, this class has been renamed to DynamicExpressionParser to avoid naming conflicts.
