### ISSUE TITLE
Is it possible to pass CustomAttribute to property using new(...) syntax? 

### ISSUE THREAD

**Issue by z4kk** [StefH/System.Linq.Dynamic.Core#227]
Some weird question :)
Is it possible to **pass(or add)** CustomAttribute to property using **new(...)** syntax?
For example: 
`customers.Select("new(Name as [SomeCustomAttribute]NameTest, Phone)");`

And DynamicClass would be like:
``` c#
class DynamicClass1
{
  [SomeCustomAttribute]
  public string NameTest { get; set }

  public string Phone { get; set; }
}
```

Or maybe any other technique to not lose CustomAttributes? 
Thanks!

**Comment by StefH** [comment]
Sorry, this is not possible with the current code.

As a workaround, you can just loop the results and add the attributes by yourself.
