### ISSUE TITLE
Cannot work with property which in base class.

### ISSUE THREAD

**Issue by PMExtra** [StefH/System.Linq.Dynamic.Core#23]
`_dbContext.Users.AsNoTracking().OrderBy("Id").ToListAsync()`

throw exception:
`No property or field 'Id' exists in type 'ApplicationUser' (at index 0)`

But it's going well with System.Linq.Dynamic.Library (without netcore)

If I override the property ` Id` in ApplicationUser, It will be ok.

(Asp.Net Core RC2，ApplicationUser based on IdentityUser)
"System.Linq.Dynamic.Core": "1.0.3"

**Comment by StefH** [comment]
See new nuget :
https://www.nuget.org/packages/System.Linq.Dynamic.Core/1.0.3.3

**Comment by PMExtra** [comment]
Very thanks. The problem is solved!!!

**Comment by StefH** [comment]
OK. I close the issue.
