### ISSUE TITLE
Extensionpoint for changing identifier token text

### ISSUE THREAD

**Issue by skriebi** [StefH/System.Linq.Dynamic.Core#232]
Hello,

given the following scenario:

A web service returns persons as a list of PersonModel classes and the web service client can query this list.
The web service client is allowed to write queries with all PersonModel properties. Additionally the client can also use additional properties not contained in the PersonModel.
E.g. `group_ID == 5.` This group_ID ist not part of the PersonModel.
The client knows nothing about the source of the data and nothing about the source structure.
It is also not an option to change the PersonModel.

The query for the result:
```csharp
var query = from p in ctx.person
            select new
            {
                p.group_ID,
                person = new PersonModel
                {
                    ID = p.person_ID.ToString(),
                    Name = p.Name,
                    Description = p.Description
                }
            };

query = query.Where("name = 'Jeff'");
```

The where-Statement will stop with an exception, because the "name" property is not a member of query result type.

The correct where statement is `query.Where("person.name = 'Jeff'")`.

I could do a string replace and prefix all PersonModel related property names in the where statement with `.person`. But this would also change the text between the quotes. If the where statement is `query.Where("name = 'Jeff' AND Description='The name is incorrect.'")`, then the name-string in the description statement would also replaced by `person.name`.

I see two possible extension points:

1. The TextParser parses the where statement and marks them as identifier tokens. At this point a dictionary or an extension method could be called to change the token text.
1. The ExpressionParser could also extended to allow the change of the text of an identifier token. This has to be done each time the text of the token is requested.

**Comment by StefH** [comment]
The best is to tell the client to use a the correct prefix `person` in case person related things are required.

Another option is to not use string replace, but regular expressions which are more powerful and precise.

**Comment by StefH** [comment]
At this moment, I'll not implement this. Maybe in future.
