### ISSUE TITLE
Does this support Json data

### ISSUE THREAD

**Issue by jnothstine** [StefH/System.Linq.Dynamic.Core#234]
I have a column in my database that is json data.  I can write a statement that looks something like this:

``` c#
.Where(x => (JsonValue(Convert(x, IJsonDataContainer).Data, "$.userInfo.userName) == "someValue' ")
```

Where `$.userInfo.userName` is a path into the json that is stored in the Data column of the table.

Does this tool support that kind of syntax?  I don't see it but I, hopefully, am missing something.

Thanks,

Jerry.

**Comment by StefH** [comment]
No sorry.

**Comment by jnothstine** [comment]
Stef,

Thanks for the quick response.  We did actually get it to do exactly what we want. ☺

Corey worked on it for a short period of time and got it to work.  Said it was quite easy.  Corey, can you please explain to Stef what you did to make it do what we want?

Thanks,

Jerry.

**Comment by jnothstine** [comment]
Hey Stef,

Want to thank you for this package.  I worked on one for three weeks and it barley got things done that I needed.  Then, I “fell” onto this one while searching for something else.  It took us less than half a day to remove ours and implement yours.  This is super cool!!

Thanks,

Jerry.

From: Jerry Nothstine
Sent: Wednesday, January 2, 2019 1:52 PM
To: 'StefH/System.Linq.Dynamic.Core' <reply@reply.github.com>
Cc: Corey Kamarainen <Corey.Kamarainen@waterstreetcompany.com>
Subject: RE: [StefH/System.Linq.Dynamic.Core] Does this support Json data (#234)

Stef,

Thanks for the quick response.  We did actually get it to do exactly what we want. ☺

Corey worked on it for a short period of time and got it to work.  Said it was quite easy.  Corey, can you please explain to Stef what you did to make it do what we want?

Thanks,

Jerry.

**Comment by StefH** [comment]
@jnothstine;

I'm glad everything worked as defined for you!

**Comment by wakuflair** [comment]
@jnothstine 

Thanks for your explanation. I learned a lot.
However I have a problem with the column name.
I constructed my query string like this: `MyTable.Where($"DbFunctions.JsonValue(\"column1\", \"$.name\"))`, but DynamicLINQ generated the SQL `JSON_VALUE('column1', '$.name')`, where the column1 is generated as a string, rather than a column name, so my query failed.

Could you give me a sample of how your `JsonExtensions` is defined and how your query string constructs?

**Comment by superjulius** [comment]
@wakuflair @jnothstine This is a quite old issue but I am facing the same problem with the column name being interpreted as a string. It must be a dumb thing but could not get it working on my end...
