### ISSUE TITLE
Error InvalidOperationException NullReferenceException

### ISSUE THREAD

**Issue by tanngocIT** [StefH/System.Linq.Dynamic.Core#235]
I have error when use it
System.InvalidOperationException: An exception was thrown while attempting to evaluate a LINQ query parameter expression. To show additional information call EnableSensitiveDataLogging() when overriding DbContext.OnConfiguring. ---> System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by StefH** [comment]
So your full code is like:
``` c#
string monthFormat = "Jan";
var valueTypes = pollens.Select($"new({monthFormat},Type)").ToDynamicList();
```

**Comment by tanngocIT** [comment]
yes. this is my full code

**Comment by StefH** [comment]
What happens if you just use normal linq?

``` c#
string monthFormat = "Jan";
var valueTypes = pollens.Select(p => new { Jan, Type });
```

And when just using normal objects (without real DB), it works.
``` c#
void Main()
{
	var q = new[] { new Pollen { Jan = 1, Type = "t" } }.AsQueryable();
	
	string monthFormat = "Jan";
	var valueTypes = q.Select($"new({monthFormat},Type)").ToDynamicList();
	valueTypes.Dump();
	
	var valueTypes2 = q.Select(p => new { p.Jan, p.Type }).ToList();
	valueTypes2.Dump();
}

public class Pollen
{
	public string Type { get; set; }
	public int Jan { get; set; }
	public int Feb { get; set; }
}
```

Maybe the `Type` is conflicting? Can you change that to `XType` ?

**Comment by StefH** [comment]
Closing issue.

If it's still a problem, answer here or create a new issue.
