### ISSUE TITLE
Missing SingleOrDefaultAsync for EntityFrameworkCore

### ISSUE THREAD

**Issue by MaklaCof** [StefH/System.Linq.Dynamic.Core#238]
I think there is no method `SingleOrDefaultAsync`.

I found [this issue](https://github.com/StefH/System.Linq.Dynamic.Core/issues/24) but it talks about `EntityFramework` not `EntityFrameworkCore`.

**Comment by StefH** [comment]
It's indeed missing.

I'm adding it now (https://github.com/StefH/System.Linq.Dynamic.Core/pull/239), I keep you posted here when a new NuGet is ready.

**Comment by StefH** [comment]
Version 1.0.9.2 will be uploaded to NuGet in some minutes.
