### ISSUE TITLE
FirstOrDefaultAsync method is missing

### ISSUE THREAD

**Issue by ehsaanwelcome** [StefH/System.Linq.Dynamic.Core#24]
Hi, 
in following query, i can not use async version of FirstOrDefault method
_db.Orders.Where($"----").Select($"---").FirstOrDefaultAsync()

**Comment by StefH** [comment]
There is no **Async** support yet, I'll take a look how to add this.

**Comment by StefH** [comment]
Questions:

- Which .Net Framework do you use ? [.net 4.5.2 ?]
- Which version from EntityFramework do you use ? [ef 6.1.3 ?]

**Comment by ehsaanwelcome** [comment]
6.1.3
4.6

**Comment by StefH** [comment]
This new functionality has been added to a new NuGet package : https://www.nuget.org/packages/EntityFramework.DynamicLinq/1.0.0

Can you please use this NuGet and check if **FirstOrDefaultAsync** is working as expected ?

**Comment by ehsaanwelcome** [comment]
It worked,
Thanks

**Comment by StefH** [comment]
OK. Thank you for verifying, I'll close the issue now.
