### ISSUE TITLE
Question: Is it possible to project without flattening the result?

### ISSUE THREAD

**Issue by Dvladd88** [StefH/System.Linq.Dynamic.Core#241]
I am storing some model, A, in a no-sql db. Inside it has properties of type B and C (each type with its own properties), something like this:

``` c#
class A {
  string topProperty
  B bProperty
  C cProperty
}

class B{
  string someString
}

class C{
  string someOtherString
}
```

I am trying to project using Select<T> and obtain a result which is not flat, but rather it maintains the hierarchy of A. 
So if I try `Select<A>("new (bProperty.someString, cProperty.someOtherString)")` , I would like to be able to get the result in this form:
``` js
A {
  B bProperty // with someString populated
  C cProperty // with someOtherString populated
}
```
But it crashes with NullRef exception, as (I presume) it does not knows how to instantiate B and C. I need the result to maintain the original hierarchical and not an Anonymous type which has a flat hierarchy containing the 2 values of someString and someOtherString.
I looked over the unit tests but could not find a similar example.

Is this something I can achieve with how Select currently works? 

Many Thanks!

**Comment by StefH** [comment]
This code should just work:
``` c#
class A
{
	public string topProperty { get; set; }
  	public B bProperty { get; set; }
  	public C cProperty { get; set; }
}

class B
{
	public string someString { get; set; }
}

class C
{
	public string someOtherString { get; set; }
}

void Main()
{
	IQueryable<A> query = new[] { new A { bProperty = new B { someString = "x" }} }.AsQueryable(); 
	var result = query.Select("new (bProperty, cProperty)");
	result.Dump();
}
```

**Comment by Dvladd88** [comment]
Thank you for taking time to respond (and format the question) ! Really appreciate your help.
What import are you using for .Dump() ?

**Comment by StefH** [comment]
.Dump() is from Linqpad. I use this for quick testing.

Is your question resolved. If yes. This issue can be closed.

**Comment by StefH** [comment]
You can use:
``` c#
IQueryable<A> query = new[] { new A { bProperty = new B { someString = "x" } } }.AsQueryable();

string predicate = $"new {typeof(A).FullName}(new {typeof(B).FullName}(\"x\" as someString) as bProperty)"; // new ConsoleAppEF2.Program+A(new ConsoleAppEF2.Program+B("x" as someString) as bProperty)/
var result = query.Select(config, predicate);
Console.WriteLine(JsonConvert.SerializeObject(result)); // [{"topProperty":null,"bProperty":{"someString":"x"},"cProperty":null}]
```
