### ISSUE TITLE
Question: Is it possible to validate expression before apply it?

### ISSUE THREAD

**Issue by mdmoura** [StefH/System.Linq.Dynamic.Core#245]
Is it possible, given a query

    .Where("City == 'London' and Orders.Count >= 10")

To validate the expression before applying it:

    "City == 'London' and Orders.Count >= 10"

**Comment by StefH** [comment]
You can use the `Parse(...)`  method from the `DynamicExpressionParser` class.

**Comment by mdmoura** [comment]
Thank you for the answer.
