### ISSUE TITLE
Parameterized SQL doesn't work for Contains, StartsWith, and EndsWith 

### ISSUE THREAD

**Issue by BradleyUffner** [StefH/System.Linq.Dynamic.Core#247]
If I use `.Where(config, "ActivityCode==@0", "AB")` it works as expected, generating the parameterized value, but `.Where(config, "ActivityCode.Contains(@0)", "A")` still inlines the value.

**Comment by StefH** [comment]
A preview NuGet is released: **1.0.10-ci-1959** ; can you test this?

See https://github.com/StefH/System.Linq.Dynamic.Core/wiki/MyGet-preview-versions for details.

**Comment by StefH** [comment]
Hello @BradleyUffner ; can you do some tests please?

**Comment by BradleyUffner** [comment]
I'll test it as soon as I get out of the meeting I'm in.

**Comment by StefH** [comment]
@BradleyUffner Did you have time to verify ?

**Comment by BradleyUffner** [comment]
I'm so sorry, The last few days have been really chaotic, and it keeps slipping my mind.  I'll do my best to test this tomorrow.

**Comment by BradleyUffner** [comment]
I just finished testing, it it seems to be fixed!  Thanks!  Sorry for the delay in testing.

**Comment by StefH** [comment]
Thanks for testing; I'll merge code to master.

I keep you informed here when a new NuGet is released.

**Comment by StefH** [comment]
Official NuGet 1.0.11 is uploaded.
