### ISSUE TITLE
DynamicExpression gone in version 1.0.3.4

### ISSUE THREAD

**Issue by rpaschoal** [StefH/System.Linq.Dynamic.Core#25]
Hello,

I can't find DynamicExpression class in version 1.0.3.4 anymore.

Was it renamed?

Thanks! Cheers.

**Comment by StefH** [comment]
Renamed to DynamicExpressionParser.

**Comment by rpaschoal** [comment]
Thank you =)

Quick question, I see you are returning "LambdaExpression" type. How can I cast it to "Expression<Func<Entity, bool>>" ?

The reason why I am asking this is because I am using it to build custom LINQs as well, based on expressions.

I tried like this but I get exception:

(Expression<Func<Entity, bool>>)Expression.Lambda(expression1, null);

**Comment by StefH** [comment]
Maybe this one helps:
https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src-console/ConsoleApp1/Program.cs#L24

**Comment by rpaschoal** [comment]
Hmmm, didn't work... I need to get that type of result without supplying the paremeters. I am getting an exception telling me I should supply the paremeters.

I am basically trying to use it as in "System.Linq.Dynamic" as it follows:

var expression1 = !String.IsNullOrEmpty(expression) ? System.Linq.Dynamic.DynamicExpression.ParseLambda< Entity, bool >(expression, null) : null;

**Comment by rpaschoal** [comment]
Oh mate, sorry! That worked =)

Thank you very much. Nice piece of work done here in this repo.

Cheers!

**Comment by StefH** [comment]
closed
