### ISSUE TITLE
Have a WhereOr method

### ISSUE THREAD

**Issue by Garwin4j** [StefH/System.Linq.Dynamic.Core#263]
Basically I have a dynamic list of where clauses to add 

think : 
```C#

foreach (clause in clauses )
{
   query = query.where(clause);
}

```

But instead of "&&" them I wish that they be "||", or be given the option (either as a parameter or a different function call, like whereOr)

**Comment by StefH** [comment]
You can maybe also use LinqKit for that, see this chapter:
https://github.com/scottksmith95/LINQKit#predicatebuilder

**Comment by Garwin4j** [comment]
Thanks for this. Instead, I just build the custom build the string for the where clause.
