### ISSUE TITLE
Linq CreateQuery throws exception

### ISSUE THREAD

**Issue by johnFA90** [StefH/System.Linq.Dynamic.Core#265]
When i try to use a dynamic query of a queriable list i get an exception only for some of the Linq functions as seen bellow.

This works fine (also `Select(...)`):

``` csharp
string query = @"@0.Where(TControl==""skip"")";
var expression = new ExpressionParser(null, query, new[] { list.AsQueryable() }, null).Parse(null);
var result = list.AsQueryable().Provider.CreateQuery(expression);
```
This throws exception (also `First(...)`, or `Last(...)`):

``` csharp
string query = @"@0.FirstOrDefault(TControl==""skip"")";
var expression = new ExpressionParser(null, query, new[] { list.AsQueryable() }, null).Parse(null);
var result = list.AsQueryable().Provider.CreateQuery(expression);
```
On the last line it throws: `System.ArgumentException: 'Argument expression is not valid'`

What am i missing? I suspect that the problem could be the return type - first enumerable and the second is element type. If so, how can i make them work both in the same query?

**Comment by johnFA90** [comment]
Issue opened also on SO:
https://stackoverflow.com/questions/55211537/linq-createquery-throws-exception

**Comment by StefH** [comment]
The first question would be ; why do you want to use this code?

Second question ; The ExpressionsParser class is not present in this library, you need to use `DynamicExpressionParser.ParseLambda`

**Comment by johnFA90** [comment]
> The first question would be ; why do you want to use this code?

I have an API that:
- accepts user input query as a single string: **userInputQuery**;
- i use the **userInputQuery** string on a generated object list to get a **result**;
- i return the **result** to the user.

> Second question ; Why not use DynamicExpressionParser.ParseLambda

I already tried that (example bellow) but the behaviour is the same:

``` csharp
class SomeClass
{
    public int SomeValue { get; set; }
}

var queryableData = new List<SomeClass>
{
    new SomeClass { SomeValue = 1 },
    new SomeClass { SomeValue = 2 },
    new SomeClass { SomeValue = 3 },
    new SomeClass { SomeValue = 4 },
    new SomeClass { SomeValue = 5 },
    new SomeClass { SomeValue = 6 },
    new SomeClass { SomeValue = 7 },
}.AsQueryable();

var userInputQuery = "@0.Where(SomeValue>5).First()"; // throws exception
// Note: "@0.Where(SomeValue>5)" will work just fine

var expression = DynamicExpressionParser.ParseLambda(null, userInputQuery, queryableData);
var result = queryableData.Provider.CreateQuery(expression.Body).ToDynamicArray<object>();
```

**Comment by StefH** [comment]
Hello @johnFA90,

Can you use this code example?
``` c#
var queryableData = new []
{
	new SomeClass { SomeValue = 1 },
	new SomeClass { SomeValue = 2 },
	new SomeClass { SomeValue = 3 },
	new SomeClass { SomeValue = 4 },
	new SomeClass { SomeValue = 5 },
	new SomeClass { SomeValue = 6 },
	new SomeClass { SomeValue = 7 },
}.AsQueryable();

var userInputQuery = "@0.Where(SomeValue > 5).First()";

var expression = DynamicExpressionParser.ParseLambda(null, userInputQuery, queryableData);
Delegate del = expression.Compile();
var result = del.DynamicInvoke() as SomeClass;
```
