### ISSUE TITLE
Timezone conversion

### ISSUE THREAD

**Issue by Enngage** [StefH/System.Linq.Dynamic.Core#268]
Hi, 

When I'm using a where condition such as 

```
.Where("RequestedDate > \"Fri, 10 May 2019 11:03:17 GMT\"")
```

the output sql query contains:

```
[RequestedDate] > '2019-05-10T13:03:17.0000000+02:00'
```

My server is running in CEST timezone and I guess that is why I get +2 hours. However, this behavior is not what I'm after as all dates in my DB are considered to be UTC and clients (browser - javascript) are providing dates always in UTC as well and thus the conversion breaks the functionality.

Is there any way to stop this behavior? Is this behavior intented? 

I figured I can just omit the zone and provide  `Fri, 10 May 2019 11:03:17 `, but this format is 'not supported' via native Javascript Date and I would have to remove it manually (which is possible and current workaround I'm using, but it doesn't feel right).

Thank you for any insights you can provide :-)

**Comment by StefH** [comment]
I need to investigate this.

Maybe add a config setting to define the datetime parse timezone.

**Comment by Enngage** [comment]
Having a config or a function that I can use to transform `DateTime` before it gets parsed would be awesome!

**Comment by StefH** [comment]
I've added a new config setting `DateTimeIsParsedAsUTC` which should be set to true in your case.

Try latest preview NuGet from:
1.0.18-ci-11429

(https://github.com/StefH/System.Linq.Dynamic.Core/wiki/MyGet-preview-versions)

**Comment by StefH** [comment]
@enngage did you have time to test this?

**Comment by StefH** [comment]
@Enngage Did you have time to test this MyGet ?

**Comment by StefH** [comment]
@Enngage Can you please test this ?

**Comment by StefH** [comment]
https://github.com/StefH/System.Linq.Dynamic.Core/pull/277

**Comment by tludusan** [comment]
Hello @StefH.

We have tested your change from PR #277. This seems to work very well, except for the case when the fields are of type nullable DateTime. Can this be fixed for nullable types as well?

PS: We would like to use your fix ASAP, when do you plan to have this merged?

Thanks,
Tudor

**Comment by StefH** [comment]
Can you please test `1.0.19-ci-11834` on myget? This one should fix nullable datetime

**Comment by tludusan** [comment]
We have tested this and it seems to work great for both DateTime and nullable DateTime now. For some reason we weren't able to find the `1.0.19-ci-11834` version from myget, but we built the sources from the branch locally, and we manually copied the DLLs.

I've noticed that the all checks have passed for PR #277. Do you have an ETA for when this will be merged? Thanks!

**Comment by StefH** [comment]
ETA = soon
