### ISSUE TITLE
np() opererator fails for (Nullable) DateTime

### ISSUE THREAD

**Issue by StefH** [StefH/System.Linq.Dynamic.Core#269]
https://github.com/StefH/System.Linq.Dynamic.Core/issues/98

**Comment by StefH** [comment]
@ani2479 ; can you please test the NuGet on MyGet. Version: 1.0.13-ci-11292

see
https://github.com/StefH/System.Linq.Dynamic.Core/wiki/MyGet-preview-versions
&
https://www.myget.org/feed/system-linq-dynamic-core/package/nuget/System.Linq.Dynamic.Core

**Comment by ani2479** [comment]
Hi,

It worked fine. I will do more testing on dates today.

Thanks.

**Comment by ani2479** [comment]
Hi,

So far everything is working as expected - Where, OrderBy, Select.

Thanks

**Comment by StefH** [comment]
https://github.com/StefH/System.Linq.Dynamic.Core/pull/270
