### ISSUE TITLE
UWP version

### ISSUE THREAD

**Issue by pellea** [StefH/System.Linq.Dynamic.Core#27]
Hello,

Is it possible to make this library compatible with UWP ?

Thanks,
Adrien.

**Comment by StefH** [comment]
It's compatible with "UAP 10.0", isn't that enough for your application ?

**Comment by pellea** [comment]
I was unable to reference the NuGet package.

**Comment by StefH** [comment]
Can you provide a simple example project ?

**Comment by StefH** [comment]
Any news?

**Comment by StefH** [comment]
@pellea Any update?

**Comment by pellea** [comment]
I built the project myself and use the dll directly. It's still not compatible with .NET Native though (due to a Emit dll, it's a known problem)

**Comment by StefH** [comment]
@pellea Should be fixed.
See https://github.com/StefH/System.Linq.Dynamic.Core/issues/33

Get the latest NuGet.

**Comment by jogibear9988** [comment]
close?

**Comment by StefH** [comment]
Yes closing this issue is fine because there is no feedback anymore from @pellea
