### ISSUE TITLE
Question: Extension method that returns Expression<Func<T, bool>> ?

### ISSUE THREAD

**Issue by ewahner** [StefH/System.Linq.Dynamic.Core#274]
I have some queries that I would like to use this library with, but I would like to just have the library return back an Expression<Func<T, bool>> so I can just call it from within my same code, with minimal changes.  Is that something that I can already do?

**Comment by StefH** [comment]
That would be like:
``` c#
var expression = DynamicExpressionParser.ParseLambda<T, bool>(config, true, "expression");
```

See also https://github.com/StefH/System.Linq.Dynamic.Core/blob/2d7b8ee16cc76ec780fb2891b2a8dd495358aee4/test/System.Linq.Dynamic.Core.Tests/DynamicExpressionParserTests.cs#L801

**Comment by StefH** [comment]
Or you can just use `ParseLambda` and cast the result.
