### ISSUE TITLE
Nuget System.Linq.Dynamic.Core 1.0.17 - Incorrect version

### ISSUE THREAD

**Issue by tranb3r** [StefH/System.Linq.Dynamic.Core#278]
The netcoreapp2.1 dll for System.Linq.Dynamic.Core in nuget 1.0.17 does not have the correct version number (1.0.16 instead of 1.0.17).
This seems to cause the following runtime error : "The located assembly's manifest definition does not match the assembly reference".
Could you please fix it ?
Thanks.

**Comment by StefH** [comment]
Yes, I will fix this in next release.

**Comment by oferns** [comment]
Wish I'd read this 2 hours ago :(

**Comment by StefH** [comment]
@tranb3r and @oferns 
Sorry for the inconvenience caused.

A new NuGet version 1.0.18 is uploaded.
