### ISSUE TITLE
Support .NET Expression string operators (AndAlso & OrElse)

### ISSUE THREAD

**Issue by kakins** [StefH/System.Linq.Dynamic.Core#279]
In my front end, I am using the .NET expression builder to generate an expression.  I am then passing the string representation of the expression to an API, where it is parsed by Dynamic LINQ.

However, Dynamic LINQ does not recognize some of the operators, such as "AndAlso".  Therefore, an expression generated by .NET resembling something like this fails: 

`"x => x > 1 AndAlso x < 5"`

It would be very helpful if the library could support these operators and other common operators generated by the .net expression library.

**Comment by StefH** [comment]
You are correct. The AndAlso is not supported it seems.

Do you know if any other commands are not supported.

**Comment by kakins** [comment]
The only other one that I've been using somewhat frequently so far is OrElse.

**Comment by StefH** [comment]
https://github.com/StefH/System.Linq.Dynamic.Core/pull/281

**Comment by StefH** [comment]
@kakins 
Can you please try preview version `1.0.18-ci-11490` on MyGet?

(see this link for info on myget : https://github.com/StefH/System.Linq.Dynamic.Core/wiki/MyGet-preview-versions)

**Comment by kakins** [comment]
I will test this as soon as I get a chance.

**Comment by StefH** [comment]
@kakins Did you have time to test this?

**Comment by StefH** [comment]
@kakins Can you please test this?

**Comment by kakins** [comment]
I'm sorry, I've been very busy.  I will try to get to it this week.

**Comment by StefH** [comment]
Code has been merged to master. New NuGet will be release in days/week. Just watch NuGet.

Closing this issue.
