### ISSUE TITLE
Generated SQL with string array.

### ISSUE THREAD

**Issue by wlaureys** [StefH/System.Linq.Dynamic.Core#282]
When dynamically generating a query that select items based upon values from an `int[]` or `string[]`. The generated SQL is different for `int[]` or `string[]` values. And only the first item of the `string[]` array is taken into account, the other values are ignored. 

**Sample code :**

```
var whereQuery = _context.Registrations.AsQueryable();

int[] intArray = new[] {1, 2, 3};
string[] array = new[] {"A001", "D444"};

whereQuery = whereQuery.Where($"@0.Contains(RegistrationId)", intArray);
whereQuery = whereQuery.Where($"@0.Contains(Code)", array);
```
**The generated SQL looks like :**
```
...
FROM [dbo].[Registrations] AS [Extent1]
WHERE ([Extent1].[RegistrationId] IN (1, 2, 3)) 
AND (( CAST(CHARINDEX([Extent1].[Code], N'A001') AS int)) > 0)
```

For the string values I would expect: 
` AND ([Extent1].[Code] IN (N'A001', N'D444') )`

Tested with version 1.0.14.0 and 1.0.18.0

**Comment by wlaureys** [comment]
Looked for hours and of course 5 minutes after posting this issue I find a similar issue #61 
#61  also contains an explanation. 

Replacing string[] by List<string> did resolve the issue. 
Still I find the difference in behavior confusing.

**Comment by StefH** [comment]
Using a List or another object like Array or IEnumerable will probably also work fine.

**Comment by StefH** [comment]
Can I close this issue?

**Comment by wlaureys** [comment]
Yes you can.
