### ISSUE TITLE
An another project ?

### ISSUE THREAD

**Issue by branciat** [StefH/System.Linq.Dynamic.Core#29]
Hi,

Why do an another project instead of pull the modification for the target netcore to the original repository ?

**Comment by StefH** [comment]
The original project "https://github.com/NArnott/System.Linq.Dynamic" (on which this one is based) has been unlisted and the "https://github.com/kahanu/System.Linq.Dynamic" is behind in functionality and testability.

So this project has the most features, documentation and tests.

**Comment by branciat** [comment]
Ok, thanks for the job.

I had started a few months ago the fork of kahanu for the netcore target before to come back to net451 because the 3rd libraries aren't compatible. Now i return to netcoreapp again, microsoft break the compatibility with net451 into the rc2 on linux :disappointed_relieved:

**Comment by StefH** [comment]
This project should be fine for Linux rc2, if there are issues, please report these here.
