### ISSUE TITLE
Question: How to truncate possibly but not necessarily nullable datetime on SQL side?

### ISSUE THREAD

**Issue by progmars** [StefH/System.Linq.Dynamic.Core#291]
I have a  `DateTime? ValidFrom` field on my EF entity.

In clear Linq, I can filter like:

`var query = queryable.Where(e => e.ValidFrom.Value.Date >= myDate);`

and it gets executed on SQL side as

`CONVERT(date, [t].[ValidFrom0]) >= @__myDate_0'`

`.Date`  might be not widely known technique because in EF people had to use DbFunctions.TruncateTime, see https://stackoverflow.com/a/40760245/217823

It seems, Linq.Dynamic currently doesn't support automatic nullable handling for `.Date` - when I try to filter by `ValidFrom.Date`  :  I get an error

`No property or field 'Date' exists in type 'DateTime?''`

However, `ValidFrom.Value.Date` seems to work fine. But I'm building the query dynamically from UI filters and I don't always know that I need to add `.value` in between.

How can I workaround this issue and compare with date only (ignoring time), also considering that my ValidFrom is nullable?

**Comment by StefH** [comment]
See also
https://stackoverflow.com/questions/57373534/how-to-get-first-day-of-month-year-etc/57418581#57418581

For Nullable DateTime, you can use the `np()` null propagating operator.

Like

``` c#
var myDate = new DateTime(2017,1,1);
var query = queryable.Where("np(it.StartDate, DateTime(1900,1,1)) > @0", myDate);
```

**Comment by progmars** [comment]
Thanks.

Will it work also if I don't know beforehand if the field is nullable or not?

I'm using it in a generic base helper class to turn UI filters into queries.

**Comment by progmars** [comment]
Actually, I'm not sure how to implement it with `np`:

I tried:
```
                var myDate = new DateTime(2019, 11, 12).Date;
                var query = queryable.Where("np(it.ValidFrom).Date >= @0", myDate);
```
and
```
                var query = queryable.Where("np(it.ValidFrom.Date) >= @0", myDate);
```
and the result is the same error: 
`No property or field 'Date' exists in type 'DateTime?''`

**Comment by StefH** [comment]
The `.Date ` will not work, you need some tricks like described in stackoverflow.

**Comment by progmars** [comment]
Ah, I see.

Ok, fortunately I was able to at least detect if the value needs `.Date`, so I invented the following workaround:

```
var t = typeof(T);
var prop = t.GetProperties().Where(p => p.Name.ToLower() == field.ToLower()).First();

// detect if it's a nullable date or not
var dateAccess = prop.PropertyType  == typeof(DateTime?) ? $"{field}.Value.Date" : $"{field}.Date";

```
