### ISSUE TITLE
Move to .NET Core RTM

### ISSUE THREAD

**Issue by qmfrederik** [StefH/System.Linq.Dynamic.Core#30]
Hi!

.NET Core was released today, however, I notice the `netstandard1.3` and other .NET Core-related versions of `System.Linq.Dynamic.Core` 1.0.4 still depend on the prerelease versions of the .NET Core assemblies (e.g. `4.0.11-rc2-24027`).

Would it be possible for you to migrate to the final versions?

Thanks!

**Comment by StefH** [comment]
Yes, I already started yesterday, but could not finish it. (I also need to update unit-test projects).

I keep you updated in this thread.

**Comment by StefH** [comment]
NuGets created, please test.

**Comment by Muchiachio** [comment]
It works, at least on my project. Thanks.

**Comment by qmfrederik** [comment]
Excellent, thanks!
