### ISSUE TITLE
Dynamic LINQ to XML

### ISSUE THREAD

**Issue by YuriGal** [StefH/System.Linq.Dynamic.Core#300]
I am trying to use Dynamic LINQ Expressions with LINQ to XML, but having troubles with dynamic parameters. E.g. for the following structure:

```
<DataCenter>
   <Server IP="1.2.3.4">
       <OS>Windows</OS>
   </Server>
   <Server IP="5.6.7.8">
       <OS>Linux</OS>
   </Server>
</DataCenter>
```
I am trying to read and parse it like this:

```
XElement XmlSource = XElement.Load(filePath)
var query = XmlSource.Elements().AsQueryable().Select("???????");
```
What do I put as a string parameter? For example if I try to retrieve IP and OS of all servers. When I try to use `Element( )` or `Attribute( )` methods of XElement I get error that XElement doesn't have such property or method.

Though `firstAtteibute` and `firstNode` seems available. And something like this works:

```
    var query = XmlSource.Elements()
             .AsQueryable()
             .Select("new (FirstAttribute.Value as IP, FirstNode.toString() as OS)");
```
I found that similar issue [was solved](https://social.msdn.microsoft.com/Forums/en-US/e341c285-cbe8-47c1-a53b-2c6e307622dd/help-using-dynamic-linq-with-xml?forum=xmlandnetfx) by updating `predefinedTypes`, Could it be done here?

**Comment by NetMage** [comment]
There should be a configuration method to add additional types to the accessible types.

**Comment by YuriGal** [comment]
I am looking at [System.Linq.Dynamic.Core.CustomTypeProviders](https://stefh.github.io/System.Linq.Dynamic.Core/html/2adefda4-0a38-b90a-4c33-ec6bcab66e8d.htm), which I think might be the right place, but can't figure it out.

**Comment by YuriGal** [comment]
There's also `System.Linq.Dynamic.Core.Parser.PredefinedTypesHelper` but it's an internal class

**Comment by NetMage** [comment]
I added an answer to your StackOverflow question. I also added an issue suggesting documenting `ParsingConfig.CustomTypeProvider` :)

**Comment by YuriGal** [comment]
@NetMage Once again, thank you so much. This is exactly what I was looking for. Linking the answer [here](https://stackoverflow.com/a/57829472/961695) in case anybody else needs it.
