### ISSUE TITLE
Add documentation for ParsingConfig.CustomTypeProvider

### ISSUE THREAD

**Issue by NetMage** [StefH/System.Linq.Dynamic.Core#301]
There is no clear documentation for how to create or use `ParsingConfig.CustomTypeProvider` in the Wiki or code.

**Comment by NetMage** [comment]
It would also be really nice if a static GlobalConfig of ParsingConfig was pre-created and used automatically by the library that could be modified by the user, rather than passing a ParsingConfig to every call.

**Comment by StefH** [comment]
1. I've added new wiki page: https://github.com/StefH/System.Linq.Dynamic.Core/wiki/CustomTypeProvider
Please review.

2. Previously the `ParsingConfig` was a global, but that introduced wrong behaviour (and you cannot use different config for different questions)
And unit-testing is impossible.

**Comment by StefH** [comment]
@NetMage did you have time to review?

**Comment by StefH** [comment]
Closing...
