### ISSUE TITLE
Problem with slashes using contains

### ISSUE THREAD

**Issue by seregvan** [StefH/System.Linq.Dynamic.Core#306]
When I try to use Where like 

```
var files = new[]
            {
                new SomeFileModel { Name = "a\\b" },
                new SomeFileModel { Name = "c" },
                new SomeFileModel { Name = "a" },
            };
string filter = "name.contains(\"\\\")";
var result = files.AsQueryable().Where(filter).Select(x => x.Name).ToList();
```

I get an error System.Linq.Dynamic.Core.Exceptions.ParseException: 'Unterminated string literal'.
Sounds reasonable as the result filter is "\\". But when I try to use this

`string filter = "name.contains(\"\\\\\")";`

The result is empty. In this case filter doesn't work.  But if I use

`string filter = "name.contains('\\')";`

it works fine. How can I do search for strings with slashes?

**Comment by StefH** [comment]
String parsing is / escaping logic is not 100% correct I think.

For now use:
``` c#
string filter = "name.Contains(@0)";
var result = files.AsQueryable().Where(filter, "\\").Select(x => x.Name).ToList();
```

**Comment by seregvan** [comment]
I think I found the problem in your parsing. I can't see the reason to do this in string literal parsing

```
if (next == '"')
{
     NextChar();
}
```

Because if I use query `"contains(\"\\\")"` it fails with unterminated literal, but if I change query to `"contains(\"\\a\")"` it works finding "\\a" string. And also if I use `"contains(\"\\\\\")"` it works with string "\\\\" (string with two real slashes).
