### ISSUE TITLE
Group by multiple columns?

### ISSUE THREAD

**Issue by jotab123** [StefH/System.Linq.Dynamic.Core#31]
Hi!

I'm working on group by queries on sqlserver. I'm trying to create groups with multiple columns dynamically and I don't know how I can do it.

Example:

**Model**

```
    public class Element
    {
        [Key]
        public int Id { get; set; }
        public double Attribute1 { get; set; }
        public double Attribute2 { get; set; }
    }
```

**Queries**

I need this query result:
`db.Element.GroupBy(el => new { el.Attribute1, el.Attribute2 })`

Dynamically:
`db.Element.GroupBy("new(Attribute1, Attribute2)")...?`

Is it possible?

Thank you very much!

**Comment by StefH** [comment]
Should be indeed something like:
`var groupResult2 = queryable.GroupBy("new (NumberPropertyAsKey, StringPropertyAsKey)");`

See unit-test https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/test/System.Linq.Dynamic.Core.Tests/QueryableTests.GroupBy.cs

**Comment by jotab123** [comment]
I think so...but, check the output.
![output](https://cloud.githubusercontent.com/assets/13152541/16418493/5cc9e49e-3d4a-11e6-9213-cee4d8f1d1e6.png)

**Comment by jotab123** [comment]
I was doing tests with Elements in memory and It works! I'm gonna report it to EntityFramework Core team.

Great job!

**Comment by StefH** [comment]
Which version from EntityFramework Core do you use?

**Comment by jotab123** [comment]
1.0.0 Final version.
I uploaded the full project here: https://github.com/jotab123/GroupByError

**Comment by StefH** [comment]
The tests in your example project looks valid? I'll check what's happening.

**Comment by jotab123** [comment]
There are no message error, but the query database result is wrong. It should be four groups instead of ten.

```
 //List test.
var resultList1 = ElementsList.GroupBy(el => new { el.Attribute1, el.Attribute2 });     //CORRECT
var resultList2 = ElementsList.AsQueryable().GroupBy("new(Attribute1, Attribute2)");    //CORRECT

 //Database tests.
var resultDb1 = db.Element.GroupBy(el => new { el.Attribute1, el.Attribute2 });         //CORRECT
var resultDb2 = db.Element.GroupBy("new(Attribute1, Attribute2)");                      //WRONG
```

Thank you!

**Comment by StefH** [comment]
The "resultDb2" is indeed wrong, but I wonder if this is a problem with 'EntityFramework Core', it looks more an issue for System.Linq.Dynamic.Core ?

**Comment by StefH** [comment]
I'll take a look.

**Comment by StefH** [comment]
For the old (6.1.3) EF, it works fine. (I did add a test project)

**Comment by StefH** [comment]
@jotab123 I tested with EF Core 1.0.1 and it still does not work, even introduced other issue, see
https://github.com/aspnet/EntityFramework/issues/6620

**Comment by jogibear9988** [comment]
it's fixed in ef now so can be closed?

**Comment by StefH** [comment]
It's fixed in the 1.1 preview version. I made a new branch in this project to test it.

However, best to keep this issue open until the final EF Core 1.1 is published.

**Comment by StefH** [comment]
Tested successfully for 1.1 preview.

**Comment by jotab123** [comment]
Great!

**Comment by StefH** [comment]
> However, best to keep this issue open until the final EF Core 1.1 is published.

**Comment by StefH** [comment]
Solved in https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.DynamicLinq/1.0.3.3
