### ISSUE TITLE
Creating lambda without type knowledge

### ISSUE THREAD

**Issue by EynsherKiel** [StefH/System.Linq.Dynamic.Core#310]
Hello  

At first - DynamicExpressionParser.ParseLambda is work very slow! Too much slow for usage in runtime. Because need compiling and create some binding map. 

At second. DynamicExpressionParser.ParseLambda want know about type in advance. Yes, it's work in simple scenario with dynamic or object. But if I add [0] that validate expression and generate exception... Why... I want see exception in runtime when I using a delegate, for me not needed validation in compile.   I understand that it's can be do for optimization, but for me you are kill all chanses for optimize your instrument. 1 way I have it's compile in Runtime with cache, but I don't want do that because runtime must work as fast as can.  

sad somehow

**Comment by EynsherKiel** [comment]
I was reread full documentation and find out type(_expr_) and that was so helpfull ) But my consern not fullfilled ) I think that it's can be removed in commonly scenarios

**Comment by StefH** [comment]
Closing...
If you still need help, create a new issue.
