### ISSUE TITLE
Please support LongCount()

### ISSUE THREAD

**Issue by yangzhongke** [StefH/System.Linq.Dynamic.Core#311]
In the DynamicQueryableExtensions.cs
There is only “int Count(this IQueryable source, string predicate, params object[] args);”
Could you please Support LongCount?
thanks

**Comment by yangzhongke** [comment]
And OrderByDescending is missing also

**Comment by StefH** [comment]
@yangzhongke 
Can you try preview versions on MyGet?

- EntityFramework.DynamicLinq.1.0.19-ci-12028
- Microsoft.EntityFrameworkCore.DynamicLinq.1.0.19-ci-12028
- System.Linq.Dynamic.Core.1.0.19-ci-12028

**Comment by StefH** [comment]
@yangzhongke Can you please test the LongCount functionality?

**Comment by StefH** [comment]
@yangzhongke can you please test?

**Comment by yangzhongke** [comment]
thanks for your reminding, I will try it later.

**Comment by yangzhongke** [comment]
It works!
Thanks for your hand working!

**Comment by StefH** [comment]
Thank you.

In a few days I will merge this to master and create a new NuGet.
