### ISSUE TITLE
After  select new xxx{x=x.x} ,OrderBy fails 

### ISSUE THREAD

**Issue by saber-wang** [StefH/System.Linq.Dynamic.Core#312]
EF core 3.0

var query = from x in db.x 
                    join y in db.y 
                              on x.id equals y.id into xy
                    from y in xy.DefaultIfEmpty()
                    select new xxx{x=x.x}

query.OrderBy("x").ToList();

System.InvalidOperationException: The LINQ expression 'OrderBy<TransparentIdentifier<XTYHB, XTZDB>, string>(
    source: Where<TransparentIdentifier<XTYHB, XTZDB>>(
        source: LeftJoin<XTYHB, XTZDB, string, TransparentIdentifier<XTYHB, XTZDB>>(
            outer: Where<XTYHB>(
                source: DbSet<XTYHB>, 
                predicate: (x) => x.YHXZ == "Z"), 
            inner: Where<XTZDB>(
                source: DbSet<XTZDB>, 
                predicate: (x0) => x0.FJCODE == "YHZT"), 
            outerKeySelector: (x) => x.YHZT, 
            innerKeySelector: (x0) => x0.CODE, 
            resultSelector: (x, x0) => new TransparentIdentifier<XTYHB, XTZDB>(
                Outer = x, 
                Inner = x0
            )), 
        predicate: (ti) => !(ti.Outer.SJLY.Equals("XSJBXXB"))), 
    keySelector: (ti) => new XTYHB{ 
        YHM = ti.Outer.YHM
    }
    .YHM)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

**Comment by saber-wang** [comment]
override attributes cause this problem

**Comment by jenscski** [comment]
@saber-wang, I have this problem, but I don't understand what you mean that override attributes cause this problem ...

**Comment by saber-wang** [comment]
@jenscski About that
class a
{
public virtual string A { get; set; }
}

class b:a
{
public override string A { get; set; }
}

It's a little too long to remember. This problem should not be caused by system.linq.dynamic.core?

**Comment by jenscski** [comment]
Thanks.
