### ISSUE TITLE
Problem with nested projection with custom type 

### ISSUE THREAD

**Issue by fnomarkh** [StefH/System.Linq.Dynamic.Core#318]
When I have a "List<T>" navigation property in my target type (ICollection or IList) and tries to make nested projection from the source type to T type, it throws "Expression can't be null" exception.
For example:
``` c#
var config = new ParsingConfig { AllowNewToEvaluateAnyType = true };
var res = _context.Blogs.Select<Blog>(config,
    $"new(Name, Posts.Select(new {typeof(Post).FullName}(Title))as Posts)")
    .FirstOrDefault();
```
Will throw the exception!

After investigating the issue, it seems that the problem is in `(TypeHelper.IsCompatibleWith())` method. It returns false if the source type is IEnumerable and the target type is not.
In `IsCompatibleWith` method, generic collections should be validated for non-value types before these lines:
``` c#
if (!target.IsValueType)
 {
       return target.IsAssignableFrom(source);
 }
```
A workaround for that is to change the type of navigation property to IEnumerable. In our case:
Change `ICollection<Post>` to `IEnumerable<Post>`.

**Comment by StefH** [comment]
Is this in .NET Framework or NetStandard ?

**Comment by fnomarkh** [comment]
I have tried in .NET Framework 4.6.1

**Comment by StefH** [comment]
Closing because behavior is as expected.
