### ISSUE TITLE
Where error

### ISSUE THREAD

**Issue by Arestis** [StefH/System.Linq.Dynamic.Core#319]
my code is `list.AsQueryable().Where("Name==@0","f");`

> at System.Linq.Enumerable.Single[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) <0x5fa0660 + 0x000ea> in <8d1cd12eb2f14ff98c296edd253f932d>:0 at System.Linq.Dynamic.Core.DynamicQueryableExtensions.GetMethod (System.String name, System.Int32 parameterCount, System.Func`2[T,TResult] predicate)

**Comment by fchiumeo** [comment]
> my code is `list.AsQueryable().Where("Name==@0","f");`


correct is
` list.AsQueryable().Where("Name=@0","f"); `

**Comment by Arestis** [comment]
> > my code is `list.AsQueryable().Where("Name==@0","f");`
> 
> correct is
> `list.AsQueryable().Where("Name=@0","f");`

it doesn`t work, error the same
