### ISSUE TITLE
TypeHelper#ParseNumber TryParse does not use InvariantCulture

### ISSUE THREAD

**Issue by mvalero** [StefH/System.Linq.Dynamic.Core#320]
When parsing a dynamic expression that contains a real literal like `12.02` or `1.0`, the resulting LambdaExpression works differently depending on the machine's configured locale.

i.e: 
Following literal expression should be parsed to a decimal:
``` c#
var l = DynamicExpressionParser.ParseLambda(false,
   new ParameterExpression[] {}, typeof(decimal), "3.21", new object[] {});
```
But in my machine (with a german locale) the resulting expression gets the value `321` instead of `3.21` ->
![image](https://user-images.githubusercontent.com/1548536/68789526-ec963b00-0645-11ea-82bd-fa50a886568b.png)

Trying the same in a machine with a US locale it works as expected.

When looking into the TypeHelper#ParseNumber method:
https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/Parser/TypeHelper.cs#L498

you can see that `decimal.TryParse(text, out e)` gets called without using the `InvariantCulture` which leads to different results depending on the locale of the machine where the code is being executed.

When calling `ParseLambda` with `3.21m` the expression get's parsed correctly.

I'm not sure if that's the expected behavior, but in my opinion both cases should work independently of the locale as the literal in an expression normaly would use `.` as a decimal separator: https://github.com/kahanu/System.Linq.Dynamic/wiki/Dynamic-Expressions#literals

**Comment by StefH** [comment]
Good point.
However I think that this behavior should be configurable. So better to add NumberStyles and/or CultureInfo to Parsing Config

**Comment by mvalero** [comment]
Having it configurable would be a nice addition, the default should still be `InvariantCulture` in my opinion to avoid unexpected behaviour.

**Comment by StefH** [comment]
@mvalero
I've created a PR, you can review this --> https://github.com/StefH/System.Linq.Dynamic.Core/pull/323

And if you want to test, you can use the `System.Linq.Dynamic.Core.1.0.20-ci-12197.nupkg` from MyGet.

**Comment by StefH** [comment]
@mvalero Can you please test version `System.Linq.Dynamic.Core.1.0.20-ci-12197` from MyGet ?

**Comment by mvalero** [comment]
@StefH Sorry for the delayed response. Looks good, I just tested the version from MyGet and it solves the problem I described.

Thx a lot.

**Comment by StefH** [comment]
@mvalero Thank you very much for verifying.
