### ISSUE TITLE
Query json in .net core 3.0

### ISSUE THREAD

**Issue by MinhMit** [StefH/System.Linq.Dynamic.Core#322]
Hello supporter,

First, sorry my Eng's not good.

Second, I have a project using entity framework core 3.0 and running SQL Server 2016 and json columns.

Example:

``` c#
public class Role
{
        public Role()
        {
            Priority = 1;
        }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Priority { get; set; }
        public Object Property { get; set; }
}
```

and DbContext:

``` c#
builder.Entity<Role>(entity =>
            {
                entity.Property(role => role.Property).HasConversion(
                    role => JsonConvert.SerializeObject(role, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }),
                    role => JsonConvert.DeserializeObject<Object>(role, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore })
                    );
                entity.HasIndex(role => new { role.Id, role.Name }).Include<Role>(role => new { role.Description, role.Property }).IsUnique();
            });
```

When i query use linq dynamic, i get an error:

Query:

``` c#
'Property.Leader.Id == 1 and Property.Location.Name == "London"'
```

and error:

`The LINQ expression 'Where....' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.`

What can i do to fix this?

Thanks for your support.

**Comment by StefH** [comment]
This is a common issue with EF 3
In this link https://docs.microsoft.com/en-us/ef/core/querying/client-eval#previous-versions it's explained in more detail.
Can you test with EF 2.x and adding that `warnings.Throw(RelationalEventId.QueryClientEvaluationWarning))` ? If you get the same error in EF 2.x, then you need to rewrite your query.

(BTW I did never use `HasConversion(...)` method to convert to and from JSON...)

**Comment by MinhMit** [comment]
> Đây là một vấn đề phổ biến với EF 3
> Trong liên kết này [https://docs.microsoft.com/en-us/ef/core/querying/client-eval#preingly-versions](https://docs.microsoft.com/en-us/ef/core/querying/client-eval#previous-versions) nó được giải thích chi tiết hơn.
> Bạn có thể kiểm tra với EF 2.x và thêm nó `warnings.Throw(RelationalEventId.QueryClientEvaluationWarning))`không? Nếu bạn gặp lỗi tương tự trong EF 2.x, thì bạn cần viết lại truy vấn của mình.
> 
> (BTW Tôi chưa bao giờ sử dụng `HasConversion(...)`phương thức để chuyển đổi sang và từ JSON ...)

Thanks for your support.
And how can i use dynamic linq with json columns to filter data?
Have an example for me?
Again, thanks for your support!

**Comment by MinhMit** [comment]
> > Đây là một vấn đề phổ biến với EF 3
> > Trong liên kết này [https://docs.microsoft.com/en-us/ef/core/querying/client-eval#preingly-versions](https://docs.microsoft.com/en-us/ef/core/querying/client-eval#previous-versions) nó được giải thích chi tiết hơn.
> > Bạn có thể kiểm tra với EF 2.x và thêm nó `warnings.Throw(RelationalEventId.QueryClientEvaluationWarning))`không? Nếu bạn gặp lỗi tương tự trong EF 2.x, thì bạn cần viết lại truy vấn của mình.
> > (BTW Tôi chưa bao giờ sử dụng `HasConversion(...)`phương thức để chuyển đổi sang và từ JSON ...)
> 
> Thanks for your support.
> And how can i use dynamic linq with json columns to filter data?
> Have an example for me?
> Again, thanks for your support!

**Comment by MinhMit** [comment]
@StefH : Hi, i tried add Throw(RelationalEventId.QueryClientEvaluationWarning)) to dbcontext with EF 2.2. But my code working fine. This error only throw in EF 3.0.
How can i use dynamic linq with json columns and any example about that?
Thanks for your support.

**Comment by StefH** [comment]
Can you provide two fully working example projects ? 
- EF 2.2
- EF 3.0

**Comment by MinhMit** [comment]
[WebApplication1.zip](https://github.com/StefH/System.Linq.Dynamic.Core/files/3859645/WebApplication1.zip)
@StefH : Here is my code for EF 2.2 and EF 3.0.
I added swagger to that projects, you can use to create and select data.
Please verify that for me.
Thanks for your support!

**Comment by StefH** [comment]
You can use dynamic linq, however you need to call `ToList()` before you do the dynamic query.

Like
``` c#
var category = _context.Categories.AsNoTracking().ToList().AsQueryable().Where(search).ToList();
```

However, this means that the all data is queried and that the filtering is done at the client side. You can see this in the SQL which is generated by above c# code.
``` sql
SELECT [c].[Id], [c].[Name], [c].[Property]
FROM [Categories] AS [c]
```

**Comment by MinhMit** [comment]
Thanks for your support.

**Comment by rochapablo** [comment]
> ```cs
> .AsNoTracking()
> ```

Following this, I get `Target object is not an ExpandoObject`
