### ISSUE TITLE
Incorrect ToDynamicListAsync(this IEnumerable source, Type type) and ToDynamicArrayAsync(this IEnumerable source, Type type) behavior

### ISSUE THREAD

**Issue by GoNextGroup** [StefH/System.Linq.Dynamic.Core#327]
Hello.

I try to use `IEnumerable.ToDynamicListAsync(Type type)`. So, it's not cast to my custom type (for example, I have problem with casting to strings).

I checked your code and possible found the reason of this unbehavior definition:

you have

```
        public static Task<List<dynamic>> ToDynamicListAsync([NotNull] this IEnumerable source, [NotNull] Type type)
        {
            Check.NotNull(source, nameof(source));
            Check.NotNull(type, nameof(type));

            return Task.Run(() => source.ToDynamicList());
        }
```

instead (possible) of 

```
        public static Task<List<dynamic>> ToDynamicListAsync([NotNull] this IEnumerable source, [NotNull] Type type)
        {
            Check.NotNull(source, nameof(source));
            Check.NotNull(type, nameof(type));

            return Task.Run(() => **source.ToDynamicList(type));**
        }
```

This possible error was also found in `ToDynamicArrayAsync([NotNull] this IEnumerable source, [NotNull] Type type)`

**Comment by StefH** [comment]
When the object is a string, only then you can cast it to string!

Example:
``` c#
var result = new List<string> { "x", "x2" }.ToDynamicList(typeof(string));
```

**Comment by StefH** [comment]
see also https://github.com/StefH/System.Linq.Dynamic.Core/blob/5863256c11e32b100c917d133c54bda4afae4d8a/test/System.Linq.Dynamic.Core.Tests/DynamicEnumerableExtensionsTests.cs

**Comment by GoNextGroup** [comment]
StefH, I know, I've just wanted to show that in your code you have problem only in async cast methods.

return Task.Run(() => **source.ToDynamicList());** <--- this code do not make any casts to the asked type.

**Comment by StefH** [comment]
Ah I see. This needs to be fixed.
