### ISSUE TITLE
Contains issue with Guid field type

### ISSUE THREAD

**Issue by kollerdroid** [StefH/System.Linq.Dynamic.Core#328]
I would like to filter a list also by a Guid type.

It works on Sql server:
```sql
where Guid like '%1ce95942%'
```

I tried it as it works in case of string fields

```cs
.Where("Guid.Contains(@0)", "1ce95942")
// I get this error:  No applicable method 'Contains' exists in type 'Guid'
```
After that I tried to use .ToString() on Guid (which is exists on Guid type)

```cs
.Where("Guid.ToString().Contains(@0)", "1ce95942")
// I get this error: No applicable method 'ToString' exists in type 'Guid'
```

How could I solve this problem?

**Comment by StefH** [comment]
You should be able to do:
`Entity3s.Where("@Guid.ToString().Contains(\"4b\")")`

1. Note that you need to escape the `Guid` property name with a `@`
2. The SQL generated is not 100% the same as you would expect (a conversion to string is done first):
``` sql
-- Region Parameters
DECLARE @p0 NVarChar(1000) = '%4b%'
-- EndRegion
SELECT [t0].[Id], [t0].[Name], [t0].[Guid]
FROM [Entity3] AS [t0]
WHERE (CONVERT(NVarChar(MAX),[t0].[Guid])) LIKE @p0
```

**Comment by kollerdroid** [comment]
It works. The generated query is a little bit others, but it does not matter in this case:
```sql
SELECT [t0].[Id], [t0].[Name], [t0].[Guid]
FROM [Entity3] AS [t0]
WHERE (CHARINDEX(N'4b', CONVERT(VARCHAR(36), [t0].[Guid])) > 0))  
```
Thank You very much!
