### ISSUE TITLE
issue when comparing different types in a rule , Operator '' incompatible with operand types.

### ISSUE THREAD

**Issue by Makrambg** [StefH/System.Linq.Dynamic.Core#333]
Hi,
I have the below example rule that selects all persons that have a profession in a certain list in addition to a different condition that has already been parsed and giving 1==1.
`var filteredMembers = MembersList.AsQueryable().Where("1 == 1 && PROFESSIONID in (19,1)")`
This condition is giving the below error:
Operator '&&' incompatible with operand types 'Boolean' and 'Int32'.
Is there a solution for that ?
note that when surrounding the conditions with "()" like below , it works fine but I'm building these conditions dynamically and can't force adding the extra "()".
`var filteredMembers = MembersList.AsQueryable().Where("(1 == 1) && (PROFESSIONID in (19,1))")`

**Comment by StefH** [comment]
Sorry, you need always `()` in case you use ` in `.

A solution for your issue would be that you just always add `()`.
