### ISSUE TITLE
Error creating Null string

### ISSUE THREAD

**Issue by rockResolve** [StefH/System.Linq.Dynamic.Core#339]
When using "select string(null)" I get the "Ambiguous invocation of 'String' constructor" error.
I was able to use this select in the old kahanu/System.Linq.Dynamic.

I need the String cast because I Concat this with a query with another and the Concat insists on matching types.

How can I get a Select to return a null string from a literal null?

**Comment by StefH** [comment]
See also this one:
https://github.com/StefH/System.Linq.Dynamic.Core/issues/284
Doe this solve your issue?

**Comment by rockResolve** [comment]
No. Constants.IsNull sees the value as "null" and returns false

**Comment by rockResolve** [comment]
When I use select string(null) in the old kahanu/System.Linq.Dynamic it works.

Diagnosis: The difference is in MethodFinder.cs IsBetterThan.

The string constructor has 8 methods, FindBestMethod finds 3 methods (Char*, SByte* & Char[]) initially applicable.
kahanu IsBetterThan returns false when CompareConversion finds the parms are equal
So FindBestMethod returns final applicable.Length = 0 and the calling ParseTypeAccess falls back to GenerateConversion which succeeds.

However System.Linq.Dynamic.Core IsBetterThan returns true when the parms are equal.
So  FindBestMethod returns final applicable.Length = 3 and the calling ParseTypeAccess throws the exception.

Not sure how you would want to fix this.

**Comment by StefH** [comment]
@rockResolve 
Can you try MyGet version `System.Linq.Dynamic.Core.1.0.20-ci-12452.nupkg` ?

**Comment by StefH** [comment]
Actually using code like `string(null)` should not call the new operator, it's just a cast.
Also when casting to nullable int, you would use : `int?(5)`.

**Comment by rockResolve** [comment]
Thanks for the quick reply. The package didn't quite work for me.
I am using the results with a concat, so need string(null), not just null. 

So I downloaded the branch to look closer. After I removed the "If only 1 argument, and the arg is ConstantExpression, just return the ConstantExpression" code, your pointer constructor removal worked well and built my string(null).
Now all my tests pass, which include testing nullable bools, ints, dates.

Are you able to remove the "If only 1 argument, and the arg is ConstantExpression, just return the ConstantExpression" code or is it there for another reason?

**Comment by StefH** [comment]
When you remove that line, the dynamic code behaves like this normal c# code:
`new string((char[]) null);` and will create an empty string, which differs from a null string!

If you need concat, can't you just use `string(\"\")` ?

**Comment by rockResolve** [comment]
Oops your right my test was falsely passing with an empty string.

However I still do really need a string(null).
I am using linq.concat (like tsql union) to join several sets, but concat insists on matching types.
I am using string(null) to ensure it is sorted first/last

**Comment by StefH** [comment]
Can you provide an simple console-app?

**Comment by rockResolve** [comment]
Finally got a simple console-app made.
I had to use z.entityframework to get my group by working correctly in core.
What is the best way to share - a PR in this repo?

**Comment by StefH** [comment]
Just create a new project on github.

If needed I can copy it and debug in my solution.

**Comment by rockResolve** [comment]
Added console-app at https://github.com/rockResolve/dlinq-demo-string-null.
Currently using System.Linq.Dynamic.Core 1.0.20-ci-12519, so string(null) raises pointer constructor error.

**Comment by rockResolve** [comment]
Also added possible System.Linq.Dynamic.Core fix with added/updated tests at:
https://github.com/rockResolve/System.Linq.Dynamic.Core/tree/Better_Error-null-string

**Comment by StefH** [comment]
Can you create a PR, I'll have to check your changes.

**Comment by rockResolve** [comment]
PR #354 
I based it on the latest master, to pick up your latest changes

**Comment by StefH** [comment]
PR is merged ; closing this issue.
