### ISSUE TITLE
Support for netcoreapp1.0?

### ISSUE THREAD

**Issue by stibay** [StefH/System.Linq.Dynamic.Core#34]
Not getting any errors when adding the package but it doesn't seem like it finds the package.
Using this under "frameworks" in project.json

    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }

**Comment by StefH** [comment]
If you take a look at https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/test/System.Linq.Dynamic.Core.Tests/project.json#L22 you see that my test project is also netcoreapp1.0

Does this answer your question?

**Comment by stibay** [comment]
Hmm ok. I might be missing something but on my MVC 5.2 app I could do OrderBy, GroupBy, Where, Select etc on a List<T> and now I am only getting errors such as:
`List<T>' does not contain a definition for 'GroupBy' and the best extension method overload 'DynamicQueryableExtensions.GroupBy(IQueryable, string, string)' requires a receiver of type 'IQueryable'`

I see that if i go to the definition on my previous app I come to this method:
` public static IEnumerable<T> Where<T>(this IEnumerable<T> source, string predicate, params object[] values);`

**Comment by StefH** [comment]
All extension methods are defined in the DynamicQueryableExtensions class : 
http://system-linq-dynamic-core.azurewebsites.net/html/a5ecbe15-aade-af7f-4860-6c5c412a34b4.htm

Note that these are all based on a `IQueryable`, so you need to convert your `List<T>` first to an `IQueryable`.

```
var qry = yourList.AsQueryable();
var result = qry.GroupBy( . . . );
```

**Comment by stibay** [comment]
Aha ok. Thank you.
