### ISSUE TITLE
ParseException: No applicable method 'Contains' exists in type 'String' System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMemberAccess(Type type, Expression instance) in ExpressionParser.cs, line 1647

### ISSUE THREAD

**Issue by itdevtech** [StefH/System.Linq.Dynamic.Core#341]
ParseException: No applicable method 'Contains' exists in type 'String'
System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMemberAccess(Type type, Expression instance) in ExpressionParser.cs
System.Linq.Dynamic.Core.Parser.ExpressionParser.ParsePrimary() in ExpressionParser.cs
System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseUnary() in ExpressionParser.cs
System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMultiplicative() in ExpressionParser.cs
System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAdditive() in ExpressionParser.cs
System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseShiftOperator() in ExpressionParser.cs
System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseComparisonOperator() in ExpressionParser.cs
System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLogicalAndOrOperator() in ExpressionParser.cs
System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIn() in ExpressionParser.cs
System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAndOperator() in ExpressionParser.cs
System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseOrOperator() in ExpressionParser.cs
System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLambdaOperator() in ExpressionParser.cs
System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseNullCoalescingOperator() in ExpressionParser.cs
System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseConditionalOperator() in ExpressionParser.cs
System.Linq.Dynamic.Core.Parser.ExpressionParser.Parse(Type resultType, bool createParameterCtor) in ExpressionParser.cs
System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(ParsingConfig parsingConfig, bool createParameterCtor, ParameterExpression[] parameters, Type resultType, string expression, object[] values) in DynamicExpressionParser.cs
System.Linq.Dynamic.Core.DynamicQueryableExtensions.Where(IQueryable source, ParsingConfig config, string predicate, object[] args) in DynamicQueryableExtensions.cs
System.Linq.Dynamic.Core.DynamicQueryableExtensions.Where<TSource>(IQueryable<TSource> source, ParsingConfig config, string predicate, object[] args) in DynamicQueryableExtensions.cs
TikTing.Controllers.ReportsController.CreateReport(ReportVM model, IFormCollection collection) in ReportsController.cs

using like this.
posts.Where(config, "Title.Contains(@0)", "my post");
where posts is IQueryable

Can you please help how to get ride of this.
using latest version of  System.Linq.Dynamic.Core 1.0.20

**Comment by StefH** [comment]
Can you provide a full working console-app example?

**Comment by itdevtech** [comment]
No, I am trying to incorporate in existing web application with EntityFrameWorkCore and IdentityFramework.

Public class Post
{
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }
        .....
}

controller Code is 
var posts = dbContext..Posts
                .Include(...)
                .AsQueryable<Post>();
Then calling where
posts = posts.Where(config, "Title.Contains(@0)", "post");//Error occurred on this line
var result = posts..ToDynamicListAsync();

**Comment by StefH** [comment]
Using netcore or net framework?

**Comment by itdevtech** [comment]
.NetCore 2.1

**Comment by itdevtech** [comment]
@StefH Is there anything i am doing wrong ?
looking for solution so i can use this library.
Thanks in advance.

**Comment by StefH** [comment]
This code just works?
``` c#
using System;
using System.Linq;
using System.Linq.Dynamic.Core;

namespace ConsoleApp1TestString
{
    class Program
    {
        static void Main(string[] args)
        {
            var posts = new[] {new Post {Title = "my post"}}.AsQueryable();
            var result = posts.Where("Title.Contains(@0)", "my post").ToDynamicList();
            foreach (var p in result)
            {
                Console.WriteLine(p.Title);
            }
        }
    }

    public class Post
    {
        public string Title { get; set; }
    }
}
```

**Comment by itdevtech** [comment]
@StefH  Yes this code works.
Now what ?

**Comment by itdevtech** [comment]
@StefH Thanks for your help. so nice of You.
Problem was i was pass arguments ArrayList but this give above error after that i convert ArrayList to Array using ToArray() and this works.
This is some kind of bug if you think so.
Thanks for Awesome work you have done.

**Comment by StefH** [comment]
Thanks.

See also
- https://github.com/StefH/System.Linq.Dynamic.Core/issues/282
- https://github.com/StefH/System.Linq.Dynamic.Core/issues/61

I probably need to add a pinned issue or some help in the wiki.

**Comment by StefH** [comment]
closing...
