### ISSUE TITLE
StartsWith/Contains/EndsWith/Like - .NET Core 3.1 Doesn't seem to work even following examples in other tickets

### ISSUE THREAD

**Issue by JohnGalt1717** [StefH/System.Linq.Dynamic.Core#346]
I have an entity with a string Name property. 

I'm trying to use dynamic linq to do a contains.

dbSet.Where(p => p.Name.Contains("somestring") works fine.

I've tried adding the static method for Like and doing this (with config having a customtypeprovider that includes the context as a type)

dbSet.Where(config, "dbContextName.Like(Name, "somestring"))

This fails saying that it can't interpret it.

I looked here from the sources: https://stackoverflow.com/questions/46212704/how-do-i-write-ef-functions-extension-method

but couldn't figure out how that applied in this case because the original wasn't tagged as a DbFunction.

Can someone once and for all answer how this is supposed to be done correctly with Dynamic Linq? (and perhaps the different variations for different versions of EF Core/EF full?)

Thanks!

**Comment by StefH** [comment]
Why would you need a custom function?

In EF3, these statements are already translated correctly?

**Comment by JohnGalt1717** [comment]
Because I'm building up oData queries based on custom parsing since the odata package is completely borked and useless for .NET Core 3.1 STILL and we're out of support for .NET Core 2.2 so I don't have time to wait for them to get around to doing what they should have done 6 months ago.

**Comment by StefH** [comment]
1] Did you see these examples (for EF 2.x)?
- https://github.com/StefH/System.Linq.Dynamic.Core/blob/6fc7fcc43b248940560a0728c4d181e191f9eec1/src-console/ConsoleAppEF2.0/Database/TestContext.cs#L24
- https://github.com/StefH/System.Linq.Dynamic.Core/blob/6fc7fcc43b248940560a0728c4d181e191f9eec1/src-console/ConsoleAppEF2.0/Program.cs#L104

2] Does Microsoft.AspNetCore.OData "7.3.0" not work for you when using Microsoft.EntityFrameworkCore.SqlServer "3.1.1" ?

3] Actually I was also thinking on writing a OData parser which uses this project to dynamically generate the where clauses. Do you plan to release this as an open source project ?

**Comment by StefH** [comment]
4] I see your point. When using in EF 3, I get:
```
System.InvalidOperationException: 'The LINQ expression 'DbSet<Car>
    .Where(c => TestContext.Like(
        matchExpression: c.Brand, 
        pattern: "%a%"))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.'
```

**Comment by JohnGalt1717** [comment]
@StefH   so, I'm using this [https://github.com/codecutout/StringToExpression](https://github.com/codecutout/StringToExpression) to parse the odata syntax. The one built in only works for odatav4, I have some bugs in there and am working on PRs to get OData4 working. So far I have essentially everything working for $filter.

The order by is the tricky part. It fails when I try and generate them using expressions. I'm trying to figure out why, and realized that all of the examples in this project are commented out for .net Core 3.1 so I can't use them to generate my order bys although they do work. I'd just rather not have a dependency on this project entirely because then my coders will use it instead of doing the right thing and we'll get SQL Injections... (been there, seen the movie.)

**Comment by ikirkpat** [comment]
I think this is what was being asked here but I'm trying to do something like so:

```
IQueryable<T> results = source.Where($"{column} LIKE \"%@0\"", value);
```
Right now, it appears there is no support for this. I tried your example above using EF.Functions.Like, but it won't work. I see you use a custom parser config but I would prefer not do that since that seems like a lot of work for our app just to get a dynamic LIKE operation. It would be nice for this to be an out-of-the-box functionality in here.

**Comment by ikirkpat** [comment]
Never mind, Just tried:
```
IQueryable<T> results = source.Where($"{column}.Contains(\"{value}\")");
```
That worked.
