### ISSUE TITLE
Client or server side evaluation?

### ISSUE THREAD

**Issue by kjkrum** [StefH/System.Linq.Dynamic.Core#347]
I encountered this library because I tried to upgrade a project to EF Core 3.x and discovered that one of the LINQ expressions was broken by the [removal of implicit client side evaluation](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#linq-queries-are-no-longer-evaluated-on-the-client). I can easily work around this by making the client side evaluation explicit. But I'd like to future-proof it against a growing database by rewriting the expression so it's evaluated on the server. I'm considering this library for that purpose.

Are expressions built with this library evaluated on the client or server? If on the client, what is this project's philosophy about exposing that? In other words, if something must be evaluated on the client, does the library invisibly throw in a `ToList()`/`AsEnumerable()`, or does it make me do that myself so I'm aware of potential performance issues? I didn't see this topic covered in the documentation.

**Comment by StefH** [comment]
This library should behave like normal Linq, except that it's dynamic, So it's server-side : IQueryable.

So making your older project (NET Core 2.x) client side evaluation explicit, you can catch all errors before upgrading to EF 3.
