### ISSUE TITLE
dynamic computed expression as string

### ISSUE THREAD

**Issue by pseudo13** [StefH/System.Linq.Dynamic.Core#348]
Hi guys,

i'm using the old fashioned Datatable in Ado.Net which provides us the Datatable.Compute method.
I can call give it an expression like dt.compute("column1 + column2 as ResultColumn").
How can i achieve this with dynamic linq.

Hope you can help and provide us with example. We tried it with list.Select("column1 + column2 as ResultColumn"), but it doesn't work.
Best regards,

**Comment by StefH** [comment]
Maybe you can try
``` c#
var qry = dt.AsQueryable()
    .Select("new(it[\"column1\"] + it[\"column2\"]) as CountryAlias)");
```
?

https://stackoverflow.com/questions/5652096/dynamic-linq-no-property-or-field-exists-in-type-datarow

**Comment by pseudo13** [comment]
Hi StefH,
unfortunately it doesn't work. Can you check? 
![image](https://user-images.githubusercontent.com/20776802/73822872-637f4200-47f7-11ea-8141-d67e25cae433.png)

**Comment by StefH** [comment]
``` c#
void Main()
{
	DataTable dt = new DataTable();
	dt.Columns.Add("x", typeof(int));
	dt.Columns.Add("y", typeof(int));
	dt.Rows.Add(1,2);
	
	var select = dt.AsEnumerable();
	select.Dump();

	var qry = select.AsQueryable().Select("new ( (int(it[\"x\"]) + int(it[\"y\"])) as plus, 42 as constant)");
	qry.Dump();
}
```

-->
![image](https://user-images.githubusercontent.com/249938/73823933-93c7e000-47f9-11ea-94b4-a8fdb8403d3b.png)

**Comment by pseudo13** [comment]
Ok. I got it. Many thanks to you.
