### ISSUE TITLE
EF Core Querying Collections

### ISSUE THREAD

**Issue by Garwin4j** [StefH/System.Linq.Dynamic.Core#350]
Hello, 
Firstly, wonderful library, thank you. Secondly, 
I get this error below when trying to write a query that queries over collections
(eg. Car.Tires.Id). I assume this is not supported but I wanted to be sure or am I doing something wrong.

`"No property or field 'Id' exists in type 'List`1'"
Position [int]:24
Source [string]:"System.Linq.Dynamic.Core"
StackTrace [string]:"   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMemberAccess(Type type, Expression instance)\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParsePrimary()\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseUnary()\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMultiplicative()\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAdditive()\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseShiftOperator()\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseComparisonOperator()\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLogicalAndOrOperator()\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIn()\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAndOperator()\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseOrOperator()\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLambdaOperator()\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseNullCoa...
TargetSite [MethodBase]:{System.Linq.Expressions.Expression ParseMemberAccess(System.Type, System.Linq.Expressions.Expression)}`

**Comment by StefH** [comment]
This is also not valid Linq,
Just use:
``` c#
var result =Cars.Select("Tires.Select(Id)");
```

**Comment by Garwin4j** [comment]
Okay, thanks.
