### ISSUE TITLE
Select using the generic method Select<TResult> throws exception when selecting nested list.

### ISSUE THREAD

**Issue by ibramn** [StefH/System.Linq.Dynamic.Core#356]
this code works fine 
`var countries = countriesQuery.Select("new (Id,Name,Cities.Select(new (Id,Name)) as Cities)").ToDynamicList();`

but when I use the generic method it throws an exception 
`var countries = countriesQuery.Select<CountryDTO>("new (Id,Name,Cities.Select(new (Id,Name)) as Cities)");`

**The exception:**
System.ArgumentNullException: Value cannot be null. (Parameter 'expression')\r\n   at System.Dynamic.Utils.ContractUtils.RequiresNotNull(Object value, String paramName, Int32 index)\r\n   at System.Dynamic.Utils.ExpressionUtils.RequiresCanRead(Expression expression, String paramName, Int32 idx)\r\n   at System.Linq.Expressions.Expression.Bind(MemberInfo member, Expression expression)\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.CreateNewExpression(List`1 properties, List`1 expressions, Type newType)\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseNew()\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIdentifier()\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParsePrimaryStart()\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParsePrimary()\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseUnary()\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMultiplicative()\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAdditive()\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseShiftOperator()\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseComparisonOperator()\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLogicalAndOrOperator()\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIn()\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAndOperator()\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseOrOperator()\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLambdaOperator()\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseNullCoalescingOperator()\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseConditionalOperator()\r\n   at System.Linq.Dynamic.Core.Parser.ExpressionParser.Parse(Type resultType, Boolean createParameterCtor)\r\n   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(ParsingConfig parsingConfig, Boolean createParameterCtor, ParameterExpression[] parameters, Type resultType, String expression, Object[] values)\r\n   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(ParsingConfig parsingConfig, Boolean createParameterCtor, Type itType, Type resultType, String expression, Object[] values)\r\n   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Select[TResult](IQueryable source, ParsingConfig config, String selector, Object[] args)\r\n   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Select[TResult](IQueryable source, String selector, Object[] args)\r\n 
Thank you.

**Comment by mccollumni** [comment]
@ibramn were you able to find a solution? I'm also unable to cast the Select to a DTO.
