### ISSUE TITLE
CreateClass Equivalent?

### ISSUE THREAD

**Issue by steamrolla** [StefH/System.Linq.Dynamic.Core#36]
I'm porting some code over from big boy .NET to Core and came across a reference to the following: 
https://github.com/kahanu/System.Linq.Dynamic/wiki/Dynamic-Expressions#dynamic-data-classes

I don't see an equivalent in this library, but the readme makes it seem like it should be here. Any help? Am I blind?

**Comment by StefH** [comment]
That's a nice WIKI page, I will copy that WIKI also into this project but I'll have to modify some text.

The code you are looking for is:
`DynamicClassFactory.CreateType(properties, _createParameterCtor);`

However, at this moment this class is **internal** so you cannot use it yet, I'll try to fix this.

**Comment by StefH** [comment]
See https://www.nuget.org/packages/System.Linq.Dynamic.Core/1.0.5.1

**Comment by StefH** [comment]
@steamrolla ; can you check if this fix is ok ?

**Comment by StefH** [comment]
Closing issue.
