### ISSUE TITLE
All and Sum in the same expression

### ISSUE THREAD

**Issue by rinaldo-rfjr** [StefH/System.Linq.Dynamic.Core#364]
Hi.

I need to avoid the 0 that is returned by Sum when there are no values in the sequence. So I tried this expression:

queryExp = "(it.All(it[\"MonthData\"]) != null) ? Sum((Double?(it[\"MonthData\"]))) : null) as Total";

it is a dictionary and MonthData is the key of the element I need to Sum. In fact, not always this element will have values and so, Sum returns 0, but I need a null. When I try to run it I get this error:

applicable aggregate method 'All(Object)' exists'

Is there any other way to check this?

Regards,
Rinaldo

**Comment by rinaldo-rfjr** [comment]
Nevermind, I got it to work.

Thanks!

**Comment by rinaldo-rfjr** [comment]
Sorry StefH, in fact it isn't solved :-(

The error has stopped, but the values are wrong

**Comment by rinaldo-rfjr** [comment]
Hi Stef,

now it's solved!

**Comment by rochapablo** [comment]
Can you share?
