### ISSUE TITLE
Null propagation cannot be used for primitive type lists (string)

### ISSUE THREAD

**Issue by Franki1986** [StefH/System.Linq.Dynamic.Core#366]
I want to parse a null propagation expression for a list with a string:

Simple test scenario:
``` c#
public class TestClass{
    public List<string> MyList {get; set;}
}
```

``` c#
var dataSource = new TestClass();
// Let MyList null...

var expressionText = "np(myList.FirstOrDefault())"
LambdaExpression e = DynamicExpressionParser.ParseLambda(ParsingConfig.Default, dataSource.GetType(),
               typeof(object), expressionText, null);
            var result = (e.Compile()).DynamicInvoke(dataSource);
```

Here I get the exception : The 'np' (null-propagation) function requires the first argument to be a MemberExpression

Null propagation for a property works:

``` c#
var expressionText = "np(myList.Count)"
LambdaExpression e = DynamicExpressionParser.ParseLambda(ParsingConfig.Default, dataSource.GetType(),
               typeof(object), expressionText, null);
            var result = (e.Compile()).DynamicInvoke(dataSource);

```

**Comment by StefH** [comment]
Can you try MyGet version `System.Linq.Dynamic.Core.1.0.23-ci-13135` ?

**Comment by Franki1986** [comment]
Looks good:

```
          var dataSource = new TestClass();
          
         var expressionText = "np(MyList .FirstOrDefault())";
         LambdaExpression e = DynamicExpressionParser.ParseLambda(ParsingConfig.Default, true, typeof(Receipt),
            typeof(object), expressionText, dataSource);
         var resultRec = (e.Compile()).DynamicInvoke(dataSource);
```

`{Param_0 => Convert(IIF(((Param_0 != null) AndAlso (Param_0.MyList != null)), Param_0.MyList .FirstOrDefault(), null))}`

**Comment by StefH** [comment]
https://github.com/StefH/System.Linq.Dynamic.Core/pull/368

**Comment by StefH** [comment]
@Franki1986 Can you do some more tests please? To make sure it works also on real database calls?

**Comment by Franki1986** [comment]
Sure, I will do it tomorow. But I am using Linqtodb not ef core. But if the expression is right I think it will also work with ef..

**Comment by Franki1986** [comment]
I am not sure what kind of test scenario I could do against a database? If I understand, I have to generate a methodExpression that could return null.

**Comment by StefH** [comment]
Instead of using DynamicExpressionParser manually, you can just use a Linq Select:

Example:
``` c#
var resultDynamic = DBContext.MyClasses.AsQueryable().Select("np(MyList.FirstOrDefault())");
```

**Comment by Franki1986** [comment]
I hobe this is getting in the right direction, because it is the closest I can create with the database and LinqToDb, because a string list cannot be mapped directly to a database table and the expression then coould only be applied to the resulting data. So I created a parent and child class for 1 to n.

```

public class Parent{
    public int Id {get; set;}
    public List<Child>ChildList {get; set;}
}

public class Child{
    public int Id {get; set;}
}
```



```
       using (var db = new DbContext())
       {
            var query = db.GetTable<Parent>().LoadWith(g => g.ChildList);
            var resultA = query .Select(c => c.ChildList.FirstOrDefault() != null).ToList();

            var query2 = query .Select("r => np(r.ChildList.FirstOrDefault()) != null", null);
            var result2 = query2 .ToDynamicList();
       }
```


Resulting expression debug string:

`                  "{Table(PARENT).LoadWith(g => g.ChildList).Select(Param_0 => (IIF(((Param_0 != null) AndAlso (Param_0.ChildList!= null)), Param_0.ChildList.FirstOrDefault(), null) != null))}";`

The result list is the same..

**Comment by StefH** [comment]
And if you get the Id and provide a default value, like:
``` c#
var query2 = query .Select("np(r.ChildList.FirstOrDefault(), 42)");
```

**Comment by Franki1986** [comment]
Sorry for the late response, I wasn't at the pc over the easter days.
So this 

`var query2 = qu.Select("np(ChildList.FirstOrDefault().Id, 42)", null);`

produces the expression:

`{Table(PARENT).LoadWith(g => g.ChildList).Select(Param_0 => IIF((((Param_0 != null) AndAlso (Param_0.ChildList != null)) AndAlso (Param_0.ChildList.FirstOrDefault() != null)), Param_0.ChildList.FirstOrDefault().Id, 42))}`

which returns 42 for Ids that would return null.

Works!
Will there be a direct nuget release or do you put this change in a future release?

**Comment by StefH** [comment]
@Franki1986 Thanks a lot for this test.
One last request : can you capture the real SQL which was produced?

**Comment by Franki1986** [comment]
```
[Table("PARENT")]
public class Parent{
    [Column("ID")]
    public int Id {get; set;}
    [Association(ThisKey="ParentId", OtherKey="Id", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
    public List<Child>ChildList {get; set;}
}

[Table("CHILD")]
public class Child{
    [Column("ID")]
    public int Id {get; set;}
    [Column("PARENT_ID")]
    public int ParentId {get; set;}
}

```

LinqToDb didn't have eager loading till version 3 (pre release), so this is the SQL that is produced for a version under 3, where for each child a subselect is done:

```
SELECT
	t1.ID
FROM
	PARENT t1

DECLARE @p1 Integer -- Int32
SET     @p1 = 24

SELECT FIRST 1
        r.ID,
		r.PARENT_ID
FROM
        CHILD r
WHERE
        r.PARENT_ID = @p1

DECLARE @p1 Integer -- Int32
SET     @p1 = 25

SELECT FIRST 1
        r.ID,
		r.PARENT_ID
FROM
        CHILD r
WHERE
        r.PARENT_ID = @p1
```
and so on...

**Comment by Franki1986** [comment]
Is this sufficent for you?

**Comment by StefH** [comment]
Yes. I will merge PR and release new version.
