### ISSUE TITLE
Dynamic Core String Compare

### ISSUE THREAD

**Issue by NickHough5** [StefH/System.Linq.Dynamic.Core#369]
Hello,

I've just run the following dynamic query to compare strings to see if the field string is greater then the term (search) string, this simply outputs the results to a table that customers can filter on.

The query is:
`$"!string.IsNullOrWhiteSpace({field}) && {field}.ToLowerInvariant().Compare(\"{term}\".ToLowerInvariant()) > 0"`

Am i missing something as i get the following exception:
`"No applicable method 'Compare' exists in type 'String'"`

Anyone got an idea?

P.S do note i've got similar comparisons for Equals, Not Equals, Contains and Not Contains, all of those works flawlessly.

**Comment by StefH** [comment]
Should it be `CompareTo(...)` ?

**Comment by NickHough5** [comment]
> Should it be `CompareTo(...)` ?

Obsolute Genius, thank you.
The original Dynamic Queries used .Compare.

I was orignally using the original, until i found that their .Contains doesn't work on lists. So switched to this and im greatful that you're actively developing this wonderful extension of LinQ.
