### ISSUE TITLE
regular expression not support

### ISSUE THREAD

**Issue by leonliuxu** [StefH/System.Linq.Dynamic.Core#372]
why not support the regex in  lambda expression?

**Comment by StefH** [comment]
Because Regular Expressions are not supported in EntityFramework (cannot be translated into SQL).

An option would be like:
https://stackoverflow.com/questions/5720987/how-to-simulate-regular-expressions-in-linq-to-sql

**Comment by leonliuxu** [comment]
Thank you for your reply.
I wanna use RulesEngine (https://github.com/microsoft/RulesEngine) in my project,  It's depend on this project, Is there any suggestion for me?

Thanks a lot

**Comment by StefH** [comment]
A cool, I did not know that project used this one.

I don't have any suggestions for you related to RegEx and using these in Lambda expressions. However, it can be used I think.
