### ISSUE TITLE
Casting a int to a nullable int will throw an error when using linq to entities"Only parameterless constructors and initializers are supported in LINQ to Entities"

### ISSUE THREAD

**Issue by lennyf** [StefH/System.Linq.Dynamic.Core#44]
Using an expression in the following format - `MyDbSet.Select("new (int?(Id))")` will throw an error if the Id property is of type int. This seems to be a bug in the original System.Linq.Dynamic project too. 

One work around I have found is you can cast it to int64 first and then a nullable int like so `MyDbSet.Select("new (int?(int64(Id)))")`  

The error only gets thrown once you try to evaluate the expression e.g. calling `Count()` on the first example

**Comment by StefH** [comment]
I did add some more unit-tests, but I'm not able to reproduce?

**Comment by StefH** [comment]
@lennyf Please test with latest code.
