### ISSUE TITLE
Take() and Skip() lose ElementType

### ISSUE THREAD

**Issue by jotab123** [StefH/System.Linq.Dynamic.Core#45]
I'm trying to build a query in different steps like:

```
IQueryable result;

result = db.DBEntity.Where("Property1 > 0");
....
var result2 = result1.Skip(1).Take(10);
```

I'm using the ElementType property to get all properties and create a table but, while result returns DBEntity as ElementType, result2 returns Object as ElementType.

Would be possible to implement Skip and Take methods that returns IQueryable of TElement?

Thank you!

Configuration:
EntityFramework Core 1.0.1
Linq Dynamic Core 1.0.5.4

**Comment by StefH** [comment]
I did create a unit-test which tests your scenario, but it seems to work fine.
Can you check the linked commit on this issue ?

**Comment by jotab123** [comment]
Your test works fine because you are getting the type from first element in the IQueryable results.

This test should fail:

```
        [Fact]
        public void SkipTestForEqualElementType()
        {
            // Arrange
            var testUsers = User.GenerateSampleModels(100).AsQueryable();

            // Act
            IQueryable results = testUsers.Where("Income > 10");
            var skipResult = results.Skip(1).Take(5);
            Assert.Equal(results.ElementType , skipResult.ElementType);
        }
```

**Comment by jotab123** [comment]
Checking another projects I found they are using IQueryable.Provider to create a query and seems to works fine. Maybe is a good aproach to solve this.

```
        public static IQueryable Take(this IQueryable source, int count)
        {
            if (source == null) throw new ArgumentNullException("source");
            return source.Provider.CreateQuery(
                Expression.Call(
                    typeof(Queryable), "Take",
                    new Type[] { source.ElementType },
                    source.Expression, Expression.Constant(count)));
        }
```

Class link: [System.Linq.Dynamic](https://github.com/kahanu/System.Linq.Dynamic/blob/master/Src/System.Linq.Dynamic/DynamicLinq.cs)

**Comment by StefH** [comment]
Thanks.

Issue is solved, new NuGet 1.0.6.0 is uploaded.

**Comment by jotab123** [comment]
Great! I was checking it and works fine.

It would be interesting that Take method could take 0 value also, an return the IQueryable instead of an error. In my case, I'm using a variable as take index and sometimes is 0, and It's valid. Actually I have to check if take = 0 and set it as 1.

Good job!

**Comment by StefH** [comment]
New version added to NuGet

**Comment by jotab123** [comment]
Works fine! thanks
