### ISSUE TITLE
Methods on type are not accessible error

### ISSUE THREAD

**Issue by jotab123** [StefH/System.Linq.Dynamic.Core#46]
Trying to call a method in Where clause returns an error: "Methods on type 'SampleModel' are not accessible"

If you add a method to your SampleModel test class:

```
public class SampleModel 
{
     //.....
     public bool TestMethod(SampleModel other)
     {
          return true;
     }
}
```

This test should fail:
```
var testUsers = User.GenerateSampleModels(100).AsQueryable();
var testUsers2 = User.GenerateSampleModels(100).ToArray();

var results = testUsers.Where("TestMethod(@0)", testUsers2);
```

EntityFramework 1.0.1
Linq Dynamic Core 1.0.6.1

**Comment by StefH** [comment]
Fixed with your PR #47 ?

**Comment by jotab123** [comment]
Yes!

**Comment by fredrikkronander** [comment]
Hi, 
I'm trying to use dynamic expressions that uses methods on the entities, in this case the User entity has a public method to get "RelatedUsers" but it fails with the message "Methods on type "UserEntity" are not accessible". Shouldn't that kind of call be possible now?

`var employees = user.ToQueryable().Select("RelatedUsers(\"Employees\")").ToDynamicList();`

Thanks!
Regards
Fredrik
