### ISSUE TITLE
Add an overload to the "ToDynamicList" method which accepts a Type

### ISSUE THREAD

**Issue by rpaschoal** [StefH/System.Linq.Dynamic.Core#48]
Hello @StefH,

Is it possible to add a new overload to the existing "ToDynamicList" extension method which accepts an instance of a Type class in order to return a typed list?

This may also come as an enhancement to the library itself since most people use it for dynamic operations which they may only know the type of their data at runtime.

As a workaround for now I did the following which is a bit nasty but it is working:

```
var genericTypeArgument = resultProperty.GetType().GetTypeInfo().GenericTypeArguments[0];

var method = typeof(DynamicEnumerableExtensions).GetMethods().Where(x => x.Name == "ToDynamicList" && x.IsGenericMethod == true).First();

var dynamicQueriedResult = resultProperty.Where(filters);

resultProperty = method.MakeGenericMethod(genericTypeArgument).Invoke(dynamicQueriedResult, new object[] { dynamicQueriedResult});
```

Many Thanks!

**Comment by StefH** [comment]
You mean the a new extension method should be added like:
```c#
public static List<dynamic> ToDynamicList([NotNull] this IEnumerable source, [NotNull] Type type)
```

Which will generate a typed result list from Type type?

**Comment by rpaschoal** [comment]
Yes @StefH! That is it?

What do you think about it? Possible, good idea?

For me that would be very useful! 

Thanks :)

**Comment by StefH** [comment]
Good idea, yes.
Possible, probably. However I'm not yet sure how to build this. Maybe reuse code from the Select() method?

**Comment by rpaschoal** [comment]
You could also reuse the code I just posted above and make a call to the existing ones you have through reflection.

I could fork it and do it if you would like me to.

Cheers!

**Comment by StefH** [comment]
Should be fixed. See new nuget.

**Comment by rpaschoal** [comment]
@StefH,

Thanks for that! I will have a look as soon as possible.

Cheers!

**Comment by StefH** [comment]
@rpaschoal Did you have time to take a look ?

**Comment by StefH** [comment]
@rpaschoal Any update?

**Comment by rpaschoal** [comment]
Hello @StefH,

I will have a look in a few days... I am currently enjoying some holidays!

Thanks :)

**Comment by StefH** [comment]
@rpaschoal Any luck ?

**Comment by StefH** [comment]
@rpaschoal Any update?

**Comment by StefH** [comment]
Closing
