### ISSUE TITLE
Can I convert int to string type?

### ISSUE THREAD

**Issue by winsonet** [StefH/System.Linq.Dynamic.Core#52]
I want to do a dynamic field search, so I need to convert all the fields to string for global search, like below:

`var expectedResult = _context.Blogs.Select(b => ((string)((int)(b.BlogId))).Contains("key"));`
`var result = _context.Blogs.AsQueryable().Select("(string((int)BlogId)).Contains(@p)");`

but I know that doesn't work, so is there another way I can do ?

Thanks!

**Comment by winsonet** [comment]
Oh, sorry, I have solved this issue, it just can use ToString() for convert to string as below:

```
var expectedResult = _context.Blogs.Select(b => ((int)(b.BlogId)).ToString().Contains("aa"));
var result = _context.Blogs.AsQueryable().Select("(int(BlogId)).ToString().Contains(\"aa\")"); 
```

but I don't know why the ToString() can't use to format a DateTime value ( My another [issue](https://github.com/StefH/System.Linq.Dynamic.Core/issues/51))

**Comment by StefH** [comment]
closing this one...
