### ISSUE TITLE
External Methods call

### ISSUE THREAD

**Issue by jotab123** [StefH/System.Linq.Dynamic.Core#53]
Hi StefH!
Are there any way to call an external method like:

```c#
public static void Method1(dynamic obj)
{
    //Do something...
}

thisQuery.Select("Method1(it)");
```

I also tried with a delegate as parameter and doesn't work.

**Comment by StefH** [comment]
I think you can only call methods which are defined on the object you are querying.

See https://github.com/StefH/System.Linq.Dynamic.Core/blob/0588b82452f36190194dec2ae209038e8d60aa31/test/System.Linq.Dynamic.Core.Tests/ExpressionTests.cs#L563

**Comment by jotab123** [comment]
Ok! Could you review this code? I'm trying to do something like this:

```
[Fact]
public void NewTest()
{
     IQueryable result;

     var dynamicList = new List<dynamic>();

     result = User.GenerateSampleModels(10).AsQueryable();

     foreach (dynamic item in result)
     {
          var newItem = SetNewName(item);
          dynamicList.Add(newItem);
     }

     result = dynamicList.AsQueryable();

     var finalResult = result.Select("UserName");
}

private dynamic SetNewName(dynamic item)
{
     item.UserName = "NewName";
     return item;
}
```

**Comment by StefH** [comment]
I think you are losing the User type along the way when you convert it to dynamic.

**Comment by jotab123** [comment]
I think so but, if I do this instead of create an IQueryable with AsQueryable() it works.
`result = dynamicList.Select(d => d.UserName);`

The type is also User if I ask to first IQueryable object.
```
result = dynamicList.AsQueryable();
var type = result.First().GetType(); //Is User type.
```

**Comment by StefH** [comment]
I guess there is no solution for this, closing this issue.
