### ISSUE TITLE
Cant compile DynamicLinqWebDocs

### ISSUE THREAD

**Issue by GoodDayToCodeHard** [StefH/System.Linq.Dynamic.Core#59]
Hi! I need some documentation for your dynamic linq, so I tried compile DynamicLinqWebDocs project. After fixing broken references I came to single error in SiteMapGenerator.cs file in \Infrastructure folder:

line 26 _sitemap = new SitemapProvider().CreateSitemap(httpContext, nodes);
No overload for method 'CreateSitemap' takes 2 arguments

**Comment by StefH** [comment]
I do not maintain this project anymore actually: see also https://github.com/StefH/System.Linq.Dynamic.Core/issues/54

You can always look at the new site, or look at the unit-tests.

Do you have a specific question ?

**Comment by StefH** [comment]
closing
