### ISSUE TITLE
Issue with nested Calls

### ISSUE THREAD

**Issue by jogibear9988** [StefH/System.Linq.Dynamic.Core#60]
Do we also have this problem: https://github.com/kahanu/System.Linq.Dynamic/pull/68

**Comment by StefH** [comment]
Hello @jogibear9988.

I'm currently adding some unit-tests, and at first glance, it seems that the issue does not exists.
However I've to double check the code changes done.

I keep you informed.

**Comment by StefH** [comment]
See last commit : https://github.com/StefH/System.Linq.Dynamic.Core/commit/52307b35faffaf083654554125ce83d18e6039a1 which adds another unit test. No issues so far...
