### ISSUE TITLE
OrderBy Chaining

### ISSUE THREAD

**Issue by mguinness** [StefH/System.Linq.Dynamic.Core#62]
I have some unexpected behavior (to me) regarding the OrderBy extension.

I have an existing IQueryable<T> instance and add an order:

`qry.AsExpandable().OrderBy(a => a.Inactive);`

Then later on I call following statement using the extension method:

`qry = qry.AsExpandable().OrderBy("Name asc");`

The resulting SQL is `ORDER BY Name, Inactive` which seems counterintuitive, I would've expected the fields to be reversed, i.e. Inactive, Name.

Is that expected behavior?  With standard LINQ to chain ordering you use OrderBy followed by ThenBy, but I don't see a ThenBy extension method in your library.

**EDIT**:  I'm wondering if something like below is possible, either externally or internal to the library:

```C#
if (qry.Expression.Type == typeof(IOrderedQueryable<T>))
    qry = qry.ThenBy("Name asc");
else
    qry = qry.OrderBy("Name asc");
```

**Comment by StefH** [comment]
Interesting ! I'll take a look.

**Comment by mguinness** [comment]
This [SO post](http://stackoverflow.com/a/3760014/310601) explains why this occurs.  I was able to modify code from a [blog post](http://aonnull.blogspot.com/2010/08/dynamic-sql-like-linq-orderby-extension.html) to create a [ThenBy extension](https://github.com/StefH/System.Linq.Dynamic.Core/files/869437/ThenByExtension.txt) to test.  I confirmed that when there is an existing sort order, you have to call ThenBy() for additional ordering.  Would it be possible to include a dynamic ThenBy() extension method in your library?

**Comment by StefH** [comment]
Should be solved. Please upgrade to latest NuGet packages.

**Comment by mguinness** [comment]
Thank you, confirmed working.
