### ISSUE TITLE
Is there Way to enter a Complex query

### ISSUE THREAD

**Issue by jogibear9988** [StefH/System.Linq.Dynamic.Core#66]
For example, I've a IEnumerable Object and would like to give this string to dynamic linq:

     "GroupBy(x=>x.Id).OrderBy(x=>x.Key).Select(x=>x.Key).Where(x=>x!=null)"

for Example smth like this
  
      aaa.Complex("GroupBy(x=>x.Id).OrderBy(x=>x.Key).Select(x=>x.Key).Where(x=>x!=null)")

and it returns a object, so the result could be everything

**Comment by StefH** [comment]
Maybe this one can help you?
https://github.com/StefH/System.Linq.Dynamic.Core/blob/10fc9a2ec8677f638210804c0ca636de021e6c9a/test/System.Linq.Dynamic.Core.Tests/ComplexTests.cs

**Comment by jogibear9988** [comment]
No. I want everything in one string.

**Comment by jogibear9988** [comment]
You see here: https://dynamiclinq.codeplex.com/SourceControl/latest#DynamicLinq/DynamicLinq/Program.cs
look at the second query

**Comment by StefH** [comment]
Ah ok. I am not sure on this, if my fork does even support this notation. Did you try this?

**Comment by jogibear9988** [comment]
I'll try... If not, I'll look to patch that this will also work!

**Comment by StefH** [comment]
Thanks a lot.

**Comment by jogibear9988** [comment]
Does not work ... :-( Now we need to look what to do...

**Comment by jogibear9988** [comment]
One problem: In my commit I removed the 

     Type type = _resultType;

Problem here is, we should only do this on the last "new" in the string. How can we decide if this is the case?

**Comment by jogibear9988** [comment]
I've now added it back, but it is a Problem if have have two select new statements, where the first one should be an anonymous type!

**Comment by StefH** [comment]
I dont have access to my pc this week. Please investigate some more, I will try to look and merge at sunday. (which branch did you take?)

**Comment by jogibear9988** [comment]
fixed

**Comment by StefH** [comment]
@jogibear9988 

Can you create a unit-test which tests all this code?

```c#
Expression ParseLambdaOperator()
        {
            Expression expr = ParseOrOperator();
            if (_textParser.CurrentToken.Id == TokenId.Lambda && _it.Type == expr.Type)
            {
                _textParser.NextToken();
                if (_textParser.CurrentToken.Id == TokenId.Identifier ||
                    _textParser.CurrentToken.Id == TokenId.OpenParen)
                {
                    var right = ParseConditionalOperator();
                    return Expression.Lambda(right, new[] { (ParameterExpression)expr });
                }
                _textParser.ValidateToken(TokenId.OpenParen, Res.OpenParenExpected);
            }
            return expr;
        }
```

I dont understand which test I should write here to cover this code.

**Comment by jogibear9988** [comment]
i'll look

**Comment by jogibear9988** [comment]
I don't know when this part of the code will be hit...

**Comment by jogibear9988** [comment]
We should also check, to support Join Operator: https://dynamiclinq.codeplex.com/discussions/471215

**Comment by StefH** [comment]
1. Code is never hit I think, I just keep it for now.
2. Create a new issue for this, and then we can see if this can be implemented.
