### ISSUE TITLE
Convert Project to VS2017

### ISSUE THREAD

**Issue by jogibear9988** [StefH/System.Linq.Dynamic.Core#67]
Is it possible to convert the Project to VS2017 and csproj?

**Comment by StefH** [comment]
I did already start the migration.
See https://github.com/StefH/System.Linq.Dynamic.Core/tree/_stef_2017upgrade

Next week I will merge this branch back to master.

However I still have some issues building and generating code coverage using appveyor and codecov.

**Comment by StefH** [comment]
Done.
All code merged to `master`.
