### ISSUE TITLE
GroupBy clause add an "Item" property when projects the query

### ISSUE THREAD

**Issue by jotab123** [StefH/System.Linq.Dynamic.Core#75]
Hi Stef,

GroupBy is adding an "extra" property called "Item" when I create a grouped query and projects it with Select.

```
//elements is a List<Element> where Element is a simple Class with a public int PropertyKey property generated
// with 0 or 1 value in a routine. 

var dynamicResult = elements.AsQueryable().GroupBy("PropertyKey").Select("new (it.key as PropertyKey)");
var result = elements.GroupBy(e => e.PropertyKey).Select(e => new { PropertyKey = e.Key}).AsQueryable();

//I think this should be true, but it isn't. dynamicResult add System.Object Item [System.String] property.
dynamicResult.ElementType.GetProperties().Count() == result.ElementType.GetProperties().Count()
```

Linq.Dynamic.Core 1.0.6.13

**Comment by jotab123** [comment]
I was trying in previous versions and works fine in 1.0.6.9. Doesn't work from 1.0.6.10.

**Comment by StefH** [comment]
This change is indeed introduced when I added `Add [] to DynamicClass` functionality.

If you need all property names, use https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/DynamicClass.cs#L282

**Comment by jotab123** [comment]
Ok, thanks! but, what is Item property? If I try to get the value throws an exception.

**Comment by StefH** [comment]
I think that when you use the same rules for getting the valid properties like https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/DynamicClass.cs#L188, all will work fine.

Or do you have a specific scenario?

**Comment by jotab123** [comment]
Using the previous example, If I try to get the value of property trhows a System.Reflection.TargetParameterCountException.

```
var property = dynamicResult.ElementType.GetProperty("Item");
var value = property.GetValue(dynamicResult.First());
```

**Comment by StefH** [comment]
The `Item` property is an indexer, so you can't use this as a normal property.

See Q+A here;
http://stackoverflow.com/questions/291359/c-sharp-reflection-indexed-properties
