### ISSUE TITLE
[Bug] Problem with DynamicExpressionParser.ParseLambda & external ParameterExpression

### ISSUE THREAD

**Issue by jogibear9988** [StefH/System.Linq.Dynamic.Core#83]
I use the Library to parse customer string to return results. For my whole expression tree, i need to use a External Parameter Expression, my call then looks like this:

       e = ((DynamicExpressionParser.ParseLambda(new[] { exp2ActionInfoObj }, typeof(object), ActionTaskDTO.Value.Value).Body) as UnaryExpression).Operand;

My Problem now is, the ParmeterExpression in exp2ActionInfoObj is not allowed to have a Name, or it will not be used as the it type. See https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/ExpressionParser.cs#L313

**Comment by StefH** [comment]
Sorry, I cannot understand what you mean.

Can you provide a full code example?

**Comment by jogibear9988** [comment]
It means, if you use a Parameter expression from outside, wich should work at the "it" Parameter, the Expressions Name has to be null, or it will not work!

**Comment by StefH** [comment]
Can you please take a look at my commit ?

- check code
- check testcases

**Comment by StefH** [comment]
Can you check ?
