### ISSUE TITLE
[Bug] DynamicClassFactory not caching generated types

### ISSUE THREAD

**Issue by HunterMcEwan** [StefH/System.Linq.Dynamic.Core#84]
Inside `DynamicClassFactory.CreateType` it appears to be attempting to cache previously generated types with the same property names.  However it is using different strategies for creating the dictionary key when doing the lookups:

```
string fullName = string.Join("|", names.Select(Escape).ToArray());

if (!GeneratedTypes.TryGetValue(fullName, out type))
```

and then later when doing the updates:

`type = GeneratedTypes.GetOrAdd(fullName + "|_" + (createParameterCtor ? "1" : "0"), type);`

**Comment by StefH** [comment]
I will take a look, thanks for reporting.

**Comment by StefH** [comment]
Code is fixed, NuGet version1.0.7.3 uploaded.

**Comment by HunterMcEwan** [comment]
Thanks for the quick response/fix!
