### ISSUE TITLE
FileNotFoundException: Could not load file or assembly 'System.Linq.Dynamic.Core'

### ISSUE THREAD

**Issue by itanev** [StefH/System.Linq.Dynamic.Core#88]
Hi,

I am trying to add dynamic linq to my .net core project, so I decided to install the System.Linq.Dynamic.Core package. It installs ok, the project compiles, but runtime I am getting:

```
FileNotFoundException: Could not load file or assembly 'System.Linq.Dynamic.Core, Version=0.0.0.0, Culture=neutral, PublicKeyToken=0f07ec44de6ac832'. The system cannot find the file specified.
File name: 'System.Linq.Dynamic.Core, Version=0.0.0.0, Culture=neutral, PublicKeyToken=0f07ec44de6ac832'
```

I installed .Net standard library 1.6.1 and I am targeting .NETCoreApp 1.1. I am trying to use it in a class library project. 

What am I missing?

**Comment by StefH** [comment]
Can you add your (test) project to github?

**Comment by StefH** [comment]
Any update?

**Comment by itanev** [comment]
Sorry, I didn't have the time to write a response. 

I solve the problem. 

It turned out that it was from the way the class library was used. The architecture of my application is Plugin based, and every plugin is a class library that is copied in a specific folder in the web project on build and loaded from there. In .net core, however, the dependent packages are loaded from the nuget cache when the application is runned in debug and the dynamic linq isn't copied in this special folder so it is never loaded because no one knows about it except the class library (Plugin), which is not referenced by anyone.

I found a way to run this in debug. You just need to add:

 <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>

in the class library (Plugin) and this will cause a sub-publish, which will copy all the package assemblies in the bin folder of the class library.

This solved my problem for now. :)

Hope this will help someone.

**Comment by StefH** [comment]
Ok. Nice to hear.
