### ISSUE TITLE
[Bug] ParseException: Operator '==' incompatible with operand types 'ObjectId' and 'ObjectId'

### ISSUE THREAD

**Issue by aveyrier** [StefH/System.Linq.Dynamic.Core#94]
When using this library with the MongoDB.Driver package, an error occurs with the `DynamicExpressionParser.ParseLambda` method while trying to compare an object containing an `ObjectId` property with another `ObjectId` object.

This kind of comparison works fine inside a classic lambda expression (e.g. `entity => entity.Id == ObjectId.Parse(id)`) but it throws with the dynamic equivalent (e.g. `"it.Id == @0"`). Other operators doesn't work neither (>, <, >=, <=, !=) even though they are defined in the struct, but the `Equals` method works fine.

_Code_

    private async Task<Todo> GetTodo(string id)
    {
        ParameterExpression[] parameters = new[]
        {
            Expression.Parameter(typeof(Todo), "it"),
        };

        LambdaExpression find = DynamicExpressionParser.ParseLambda(parameters, typeof(bool), "it.Id == @0", ObjectId.Parse(id));

        return await _db.GetCollection<Todo>("Todos")
            .Find((Expression<Func<Todo, bool>>)find)
            .Limit(1)
            .SingleOrDefaultAsync();
    }

_Error_

    ParseException: Operator '==' incompatible with operand types 'ObjectId' and 'ObjectId'

_Stacktrace_

    System.Linq.Dynamic.Core.ExpressionParser.CheckAndPromoteOperands(Type signatures, string opName, ref Expression left, ref Expression right, int errorPos)
    System.Linq.Dynamic.Core.ExpressionParser.ParseComparisonOperator()
    System.Linq.Dynamic.Core.ExpressionParser.ParseLogicalAndOrOperator()
    System.Linq.Dynamic.Core.ExpressionParser.ParseIn()
    System.Linq.Dynamic.Core.ExpressionParser.ParseAndOperator()
    System.Linq.Dynamic.Core.ExpressionParser.ParseOrOperator()
    System.Linq.Dynamic.Core.ExpressionParser.ParseLambdaOperator()
    System.Linq.Dynamic.Core.ExpressionParser.ParseNullCoalescingOperator()
    System.Linq.Dynamic.Core.ExpressionParser.ParseConditionalOperator()
    System.Linq.Dynamic.Core.ExpressionParser.Parse(Type resultType, bool createParameterCtor)
    System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(bool createParameterCtor, ParameterExpression[] parameters, Type resultType, string expression, Object[] values)
    System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(ParameterExpression[] parameters, Type resultType, string expression, Object[] values)
    TodoList.Controllers.TodosController+<GetEntity>d__4.MoveNext() in TodosController.cs
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    System.Runtime.CompilerServices.TaskAwaiter.GetResult()
    TodoList.Controllers.TodosController+<Get>d__3.MoveNext() in TodosController.cs
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__27.MoveNext()
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__25.MoveNext()
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
    Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
    Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
    Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
    Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeAsync>d__20.MoveNext()
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

**Comment by StefH** [comment]
Maybe when that `ObjectId` property implements the interface `IComparable` it can work ?
See https://msdn.microsoft.com/en-us/library/system.icomparable(v=vs.110).aspx

Else can you provide the full class from `ObjectId` ?

**Comment by aveyrier** [comment]
`ObjectId` implements the interface `IComparable<ObjectId>`. You can see below the full class (or you can see it here if you want the full implementation : [https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Bson/ObjectModel/ObjectId.cs](https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Bson/ObjectModel/ObjectId.cs)).

    public struct ObjectId : IComparable<ObjectId>, IEquatable<ObjectId>, IConvertible
    {
        public ObjectId(byte[] bytes);
        public ObjectId(string value);
        public ObjectId(DateTime timestamp, int machine, short pid, int increment);
        public ObjectId(int timestamp, int machine, short pid, int increment);

        public static ObjectId Empty { get; }
        public short Pid { get; }
        public int Machine { get; }
        public int Timestamp { get; }
        public int Increment { get; }
        public DateTime CreationTime { get; }

        public static ObjectId GenerateNewId();
        public static ObjectId GenerateNewId(DateTime timestamp);
        public static ObjectId GenerateNewId(int timestamp);
        public static byte[] Pack(int timestamp, int machine, short pid, int increment);
        public static ObjectId Parse(string s);
        public static bool TryParse(string s, out ObjectId objectId);
        public static void Unpack(byte[] bytes, out int timestamp, out int machine, out short pid, out int increment);
        public int CompareTo(ObjectId other);
        public bool Equals(ObjectId rhs);
        public override bool Equals(object obj);
        public override int GetHashCode();
        public byte[] ToByteArray();
        public void ToByteArray(byte[] destination, int offset);
        public override string ToString();

        public static bool operator ==(ObjectId lhs, ObjectId rhs);
        public static bool operator !=(ObjectId lhs, ObjectId rhs);
        public static bool operator <(ObjectId lhs, ObjectId rhs);
        public static bool operator >(ObjectId lhs, ObjectId rhs);
        public static bool operator <=(ObjectId lhs, ObjectId rhs);
        public static bool operator >=(ObjectId lhs, ObjectId rhs);
    }

**Comment by StefH** [comment]
I will take a look.

**Comment by loob91** [comment]
Are you sure this is closed ? 

When I use this code :
`var _expression = DynamicExpressionParser.ParseLambda<T, bool>(ParsingConfig.Default, false, _filterString, eavcustomattributes.id, _value.ToString());`

Result is :
`Param_1.value == 12/01/2017 00:00:00`

And then I have the error :
