### ISSUE TITLE
Has no assembly version number.

### ISSUE THREAD

**Issue by ngbrown** [StefH/System.Linq.Dynamic.Core#95]
At least as of 1.0.7.6, the released NuGet package adds to the Visual Studio project as having no version number:

```xml
    <Reference Include="System.Linq.Dynamic.Core, Version=0.0.0.0, Culture=neutral, PublicKeyToken=0f07ec44de6ac832, processorArchitecture=MSIL">
      <HintPath>..\packages\System.Linq.Dynamic.Core.1.0.7.6\lib\net46\System.Linq.Dynamic.Core.dll</HintPath>
    </Reference>
```

**Comment by StefH** [comment]
Is this a blocking issue ?

**Comment by ngbrown** [comment]
I don't think so. I have a pull request in to NHibernate to use this version of the library, but it hasn't been merged yet.

I'm letting you know so you can resolve it in the future.

**Comment by jogibear9988** [comment]
can this be closed?

**Comment by StefH** [comment]
@ngbrown : Any update
