### ISSUE TITLE
Async support for ToDynamicList()

### ISSUE THREAD

**Issue by borisdj** [StefH/System.Linq.Dynamic.Core#96]
After dynamic select when enumerating I there is ToDynamicList() method but no async version of the same ToDynamicListAsync() that would propagate async call till bottom.
Could this feature be added, because I am using EFCore(1.1.2) and have made most methods in Controller and Repository to be async for efficiency.

**Comment by StefH** [comment]
Can you provide a code-example how you intend to use this ?

**Comment by borisdj** [comment]
For example in Controller (Generic one) there is regular Get method and it is Async:
````
public virtual async Task<IActionResult> Get(string args)
{
    var q = repository.Query();
    // some more code for paging and filtering
    // ...
    return Ok(await q.ToListAsync());
````
Then in the same Controller I also have action Lookup method like this:
````
[HttpGet("Lookup")]
public IActionResult Lookup(string search)
{
    var q = repository.Query();
    string idProperty = typeof(Entity).Name + "Id";
    string textProperty = GetLookupPropertyName();
    string clause = $"{textProperty}.Contains(@0)";
    if (!String.IsNullOrWhiteSpace(search))
    {
        q = q.Where(clause, search);
    }
    q = q.OrderBy(textProperty);
    q = q.Take(100);
    
    var result = q.Select($"new ({idProperty} as id, {textProperty} as text)");
    return Ok(result.ToDynamicList());
}
````

So I was considering making that one alse async but that would require **ToDynamicListAsync()**;

**Comment by StefH** [comment]
OK, I will take a look.

**Comment by StefH** [comment]
Some notes:

1] Your example code allows sql-injection (you provide the `search` parameter external input)

2] The extension methods I've created (see point 3) are _fake_, they are not really async.

3] Code be found here : https://github.com/StefH/System.Linq.Dynamic.Core/commit/ed57240198def66f37c39490df2785ab69f13c3f#diff-94779ab3305c4d04396ee3e68380908c
if this is ook, I create a new Nuget.

**Comment by borisdj** [comment]
1) Shouldn't the @(placeholder) be made into lambda argument(=>) instead of concatenating, that makes it safe from "Linq injection" attack.
If not, what would be best way to escape the string?

2) I was thinking more of real async, fake will have the same efficiency so no gain there.
I haven't yet look deep into source of the library, so I'm not sure how you implemented this under the hood and if it even possible to make full async or if it is too complex.

**Comment by StefH** [comment]
1] It's not a real `sql-injection`, but you expose the **search** criteria to the outside world, which means that you can enter whatever you like and that will be executed.

2] This file https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src/Microsoft.EntityFrameworkCore.DynamicLinq/EFDynamicQueryableExtensions.cs defines some methods which are **really** ASYNC.

**Comment by borisdj** [comment]
1) Search has to exposed to client, how else could it be done.
Is there some better way to achieve the same ?

2) I'll take a look into Asynchronous implementation.

**Comment by StefH** [comment]
If you need some more help for search, open a new issue.
