### ISSUE TITLE
Feature: Add the "?." operator (null-conditional operator) to support navigation properties with null values

### ISSUE THREAD

**Issue by jotab123** [StefH/System.Linq.Dynamic.Core#98]
Hi Stef,

I'm trying to project a sequence of items with a related property (object) which in some cases is null.

Having this classes:

```
  public class Item
  {
      public int Id { get; set; }
      public RelatedItem Related { get; set; }
  }

  public class RelatedItem
  {
      public string Value { get; set; }
  }
```

Consider this scenario:

```
var listItem = new List<Item>();

for (int i = 0; i < 100; i++)
{
    listItem.Add(new Item
    {
       Id = i,
       Related = i % 2 == 0 ? new RelatedItem{ Value = i % 4 == 0 ? "Related value " + i : null } : null
    });
}

var result1 = listItem.Select(i => i.Related?.Value);
var result2 = listItem.AsQueryable().Select("Related.Value");
```

Result1 works fine and has the expected result (a list of items with Related.Value value or null, in case of Item has Related object assigned or not) but Result2 generates an object reference exception. Is there any way to achieve this?

Thanks!

System.Linq.Dynamic.Core version 1.0.7.6

**Comment by StefH** [comment]
You could use the `isnull(a,b)` operator or the `??` operator.

**Comment by jotab123** [comment]
It seems not to work with navigation properties. Ex:
```
var result2 = listItem.AsQueryable().Select("Related.Value ?? null");
//or
var result2 = listItem.AsQueryable().Select("isnull(Related.Value,null)");
```
Throws the exception.

Finally, I could solve it with:
`var result2 = listItem.AsQueryable().Select("Related == null ? null : Related.Value");`

It would be great for future versions if you consider supporting the ? operator to improve this kind of queries.

Thanks again!

**Comment by StefH** [comment]
Actually you want the `?.` operator ?

**Comment by jotab123** [comment]
Yes. I'm having problems because the implicit conversion of types. In the example before, if Value of RelatedItem is a non-nullable type (double, int...) I cannot use a expression like "Related == null ? null : Related.Value" because throws an exception.

**Comment by StefH** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-conditional-operators

**Comment by StefH** [comment]
@jotab123 
I found out that it's not supported for Lambda expressions : **An expression tree lambda may not contain a null propagating operator**

See also here:
https://stackoverflow.com/questions/44681362/an-expression-tree-lambda-may-not-contain-a-null-propagating-operator

**Comment by peter-base** [comment]
Hi,
I am in the same scenario trying to sort a List of objects by their navigation properties.
How did you ended up sorting by the navigation property (RelatedItem.Value)?

Thank you

**Comment by jotab123** [comment]
Hi @peter-base,
I finally use default values and cast the property to its's nullable type. Ex:

> var propertyType =  people.AsQueryable().ElementType.GetProperty("Value").PropertyType;
> var defaultValue = Activator.CreateInstance(propertyType); //Returns default value.
> var typeName = propertyType.Name;
> var query = $"Relation == null ? {defaultValue} : {typeName}?(Relation.Id)";
> var result=  listItems.AsQueryable().OrderBy(query);

Hope it helps!

**Comment by jotab123** [comment]
Hi @peter-base ,
You can use something like:

```
var relatedItemType = people.AsQueryable().ElementType.GetProperty(prop1).PropertyType;
var valueTypeName = relatedItemType.GetProperty(prop2).PropertyType.Name;

var query = $"{prop1} == null ? null : {valueTypeName}?{propertyName}"
var orderedItems = listItems.AsQueryable().OrderBy(query);
```

Hope it helps!

**Comment by StefH** [comment]
I have to take a look at your code and update some unit tests.

**Comment by StefH** [comment]
Another option would be to pre-process the string, so that

``` cs
"it.Relation1?.Relation2?.Id != null"
```

becomes

``` cs
"(it.Relation1 != null ? (it.Relation1.Relation2 != null ? it.Relation1.Relation2.Id : null) : null) != null"
```

**Comment by AmbroiseCouissin** [comment]
@StefH Hi, 

It's what I did on my side. This is how I do it:

```
        private static string IgnoreIfNull(string fieldNames)
        {
            string[] splits = fieldNames.Split('.');
            for (int i = 0; i < splits.Count() - 1; i ++)
            {
                string toBeReplaced = string.Join('.', splits.Take(i + 1));
                fieldNames = fieldNames.Replace(toBeReplaced, $"{toBeReplaced} == null ? null : ({toBeReplaced}");
            }

            for (int i = 0; i < splits.Count() - 1; i++)
                fieldNames += ")";

            return fieldNames;
        }
```

It will transform:

```
"it.Relation1.Relation2.Id"
```

into

```
"(it == null ? null : (it.Relation1 == null ? null : (it.Relation1.Relation2 == null ? null : it.Relation1.Relation2.Id)))"
```

**Comment by StefH** [comment]
@AmbroiseCouissin This looks like a possible solution, however where to execute this code?

**Comment by AmbroiseCouissin** [comment]
@StefH In my case, I use this way:
```
list = list.AsQueryable().OrderBy($"{IgnoreIfNull("it?.Relation1?.Relation2?.Id")} {sort.Type}");
```

**Comment by 1dot44mb** [comment]
Any progress on this? 

By the way @AmbroiseCouissin I wrote something like your code. This is more failproof and also null-checks even if no null coalescing operator is defined:

```csharp
public static class DynamicQueryExtensions
{
    public static string ConvertToNullableNested(string expression, string result = "", int index = 0)
    {
        //Transforms => "a.b.c" to "(a != null ? (a.b != null ? a.b.c : null) : null)"
        if (string.IsNullOrEmpty(expression))
            return null;
        if (string.IsNullOrEmpty(result))
            result = expression;
        var properties = expression.Split(".");
        if (properties.Length == 0 || properties.Length - 1 == index)
            return result;
        var property = string.Join(".", properties.Take(index + 1));
        if (string.IsNullOrEmpty(property))
            return result;
        result = result.Replace(expression, $"({property} != null ? {expression} : 0)");
        return ConvertToNullableNested(expression, result, index + 1);
    }
}
```

I use it the same way you specified:
```csharp
query.OrderBy($"{DynamicQueryExtensions.ConvertToNullableNested("Entity.Relation1.Relation2.Id")} desc");
```

**Comment by StefH** [comment]
@1dot44mb 

Thanks. I did fix a small issue and added generic support.

``` c#
        public static string ConvertToNullableNested<T>(string expression, object defaultValue = null)
	{
		return ConvertToNullableNested<T>(expression, string.Empty, 0, defaultValue);
	}

	public static string ConvertToNullableNested<T>(string expression, string result, int index, object defaultValue)
	{
		if (string.IsNullOrEmpty(expression))
		{
			return null;
		}

		if (string.IsNullOrEmpty(result))
		{
			result = expression;
		}

		string[] properties = expression.Split('.');
		if (properties.Length == 0 || properties.Length - 1 == index)
		{
			if (typeof(T).IsValueType)
			{
				return result.Replace(expression, $"{typeof(T).Name}?({expression})");
			}

			return result;
		}

		string property = string.Join(".", properties.Take(index + 1));
		if (string.IsNullOrEmpty(property))
		{
			return result;
		}

		string defaultReplacement = defaultValue != null ? defaultValue.ToString() : "null";
		result = result.Replace(expression, $"({property} != null ? {expression} : {defaultReplacement})");
		return ConvertToNullableNested<T>(expression, result, index + 1, defaultValue);
	}
```

Can be used like:
``` c#
string finalT = DynamicQueryExtensions.ConvertToNullableNested<int>("it.Relation1.Relation2.Id");
// (it != null ? (it.Relation1 != null ? (it.Relation1.Relation2 != null ? Int32?(it.Relation1.Relation2.Id) : null) : null) : null)

string finalTDef = DynamicQueryExtensions.ConvertToNullableNested<int>("it.Relation1.Relation2.Id", default(int));
// (it != null ? (it.Relation1 != null ? (it.Relation1.Relation2 != null ? Int32?(it.Relation1.Relation2.Id) : 0) : 0) : 0)

```

**Comment by StefH** [comment]
@1dot44mb 
I did some more research and I've update the code in this PR https://github.com/StefH/System.Linq.Dynamic.Core/pull/222 to support automatic casting to nullable valuetypes.

So this code will work now:
``` c#
var r1 = q.Select("it != null && it.NestedDto2 != null ? it.NestedDto2.Id : null");
```

Previously you need to use this code:
``` c#
var r1 = q.Select("it != null && it.NestedDto2 != null ? int?(it.NestedDto2.Id) : null");
```

This new logic can be used in combination with `ConvertToNullableNested` helper method.

A simpler approach for that helper method can also be:
``` c#
string expression = "it.Relation1.Relation2.Id";
string[] properties = expression.Split('.');
	
var list = new List<string>();
for (int idx = 0; idx < properties.Length - 1; idx++)
{
    string property = string.Join(".", properties.Take(idx + 1));
    list.Add($"{property} != null");
}

string str = $"({string.Join(" && ", list)} ? {expression} : null)";
```
This code generates a string like:
> (it != null && it.Relation1 != null && it.Relation1.Relation2 != null ? it.Relation1.Relation2.Id : null)

**Comment by 1dot44mb** [comment]
Thanks.
PR #222 has been a great addition for dynamic Select and OrderBy parameters. In my application, OrderBy parameter is sent from the client table so it can be any column header (including nested properties). Without #222 ; `ConvertToNullableNested` did not work for me because i couldn't know the type of nested property before sending it to OrderBy extension method.

**Comment by StefH** [comment]
If you want to this, you can already use this NuGet:
https://www.myget.org/feed/system-linq-dynamic-core/package/nuget/System.Linq.Dynamic.Core/1.0.9.1-ci-1527

**Comment by StefH** [comment]
@jotab123 
@peter-base 
@1dot44mb 
@AmbroiseCouissin 

If you have time, can you do some testing with this NuGet:
https://www.myget.org/feed/system-linq-dynamic-core/package/nuget/System.Linq.Dynamic.Core/1.0.9.1-ci-1530

Null Propagating has been implemented like:
``` c#
var q1 = q.Select("np(it.NestedDto2.NestedDto3.Id, 0)"); // returns int's

// or

var q1 = q.Select("np(it.NestedDto2.NestedDto3.Id)"); // returns nullable int's
```

**Comment by StefH** [comment]
@david-garcia-garcia : Maybe you also have some time to verify this?

**Comment by StefH** [comment]
Hello
@jotab123
@peter-base
@1dot44mb
@AmbroiseCouissin

I would really appreciate if someone could verify if this logic works as expected.

**Comment by StefH** [comment]
Hello
@jotab123
@peter-base
@1dot44mb
@AmbroiseCouissin

I would really appreciate if someone could verify if this logic works as expected.

**Comment by 1dot44mb** [comment]
Dear @StefH I really appreciate the hard work. Until new year, i am a bit busy with some deadlines and projects. After that, i will happily test the nuget. Sorry for not being able to help sooner.
Best regards.

**Comment by StefH** [comment]
@1dot44mb Thanks for your help.

**Comment by StefH** [comment]
@1dot44mb Did you have time to check this new code?

**Comment by StefH** [comment]
Hello @jotab123, @peter-base, @1dot44mb, @AmbroiseCouissin : can you please test this functionality?

**Comment by StefH** [comment]
closed via PR

**Comment by MaklaCof** [comment]
@StefH 
Hi, should this work:
```
public class DbUser
{
    public int? PartnerId {get;set;}
    public DbPartner Partner {get;set;}
}

public class DbPartner
{
    public int Id {get;set;}
    public string Title {get;set;}
}
```
? Because I get exception (version `1.0.10`):

> An expression tree lambda may not contain a null propagating operator.


for
```
.Select("new(Partner?.Title)")
```

Without `?.` I get

> Nullable object must have a value

**Comment by StefH** [comment]
@MaklaCof 
you have to use:
``` c#
var q1 = q.Select("np(it.NestedDto2.NestedDto3.Id, 0)"); // returns int's

// or

var q1 = q.Select("np(it.NestedDto2.NestedDto3.Id)"); // returns nullable int's
````

**Comment by StefH** [comment]
I probably should have added this to the `An expression tree lambda may not contain a null propagating operator.` exception message...

**Comment by ani2479** [comment]
Hi, 

I'm trying to use the np function on a Where:

e.g User.Contact.FirstName.ToLower().Contains("or") where the User can be null, so I was trying to get the User?.Contact?.FirstName.

Maybe I don't really know how to use your library, but can you help me?

Entity.Where ("np(User.Contact.FirstName.ToLower().Contains(\"tor\")") and I get The 'np' (null-propagation) function requires the first argument to be a MemberExpression

Maybe you see something I don't. Thanks.

**Comment by StefH** [comment]
If the **User** can be null, just use this code

``` c#
Entity.Where ("User != null && User.Contact.FirstName.ToLower().Contains(\"tor\")");
```

**Comment by ani2479** [comment]
Thanks. is there no way to use the np with the Where?

Thanks again

**Comment by StefH** [comment]
Sure you can use the `np` in Where.

`Orders.AsQueryable().Where("np(Customer.City, \"\").Contains(\"e\")").Dump();`

results in:

``` sql
-- Region Parameters
DECLARE @p0 NVarChar(1000) = ''
DECLARE @p1 NVarChar(1000) = '%e%'
-- EndRegion
SELECT [t0].[OrderID], [t0].[CustomerID], [t0].[EmployeeID], [t0].[OrderDate], [t0].[RequiredDate], [t0].[ShippedDate], [t0].[ShipVia], [t0].[Freight], [t0].[ShipName], [t0].[ShipAddress], [t0].[ShipCity], [t0].[ShipRegion], [t0].[ShipPostalCode], [t0].[ShipCountry]
FROM [Orders] AS [t0]
LEFT OUTER JOIN [Customers] AS [t1] ON [t1].[CustomerID] = [t0].[CustomerID]
WHERE (
    (CASE 
        WHEN [t0].[CustomerID] IS NOT NULL THEN [t1].[City]
        ELSE CONVERT(NVarChar(15),@p0)
     END)) LIKE @p1
```

**Comment by ani2479** [comment]
Thanks,

Everything seems to be working, except for dates. If I do .Where("np(Customer.EndDate) ==  DateTime.Today), we are getting a System.DateTime cannot be null value.

I will try a couple more things.

**Comment by StefH** [comment]
You mean this error?
> ArgumentException: GenericArguments[0], 'System.Nullable`1[System.DateTime]', on 'System.Nullable`1[T]' violates the constraint of type 'T'.

**Comment by ani2479** [comment]
Hi, yes.

It is fine if we use any other null columns

**Comment by StefH** [comment]
I've created a new Issue

**Comment by Franki1986** [comment]
Hi,
is ther also a way to generate this for lists?

I hae an expression like this where e.g. myList is a srting lis and a member of dataSource;

```
var expressionText = "np(myList).FirstOrDefault"

LambdaExpression e = DynamicExpressionParser.ParseLambda(ParsingConfig.Default, false, dataSource.GetType(),
               typeof(object), expressionText, null);
            var result = (e.Compile()).DynamicInvoke(dataSource);
```

does not work as expression, the LambdaExpression looks as following:

`{Param_0 => Convert(IIF((Param_0 != null), Param_0.myList, null).FirstOrDefault())}`

The C# way would look like this:

`myList?.FirstOrDefault()`

what would work..

**Comment by StefH** [comment]
What happens if you use 
``` c#
var expressionText = "np(myList.FirstOrDefault)"
```

**Comment by Franki1986** [comment]
np(myList.FirstOrDefault) throws an exception with:

`{"No property or field 'FirstOrDefault' exists in type 'List`1'"}`

**Comment by StefH** [comment]
and
`var expressionText = "np(myList.FirstOrDefault())"`

**Comment by Franki1986** [comment]
Exception = {"The 'np' (null-propagation) function requires the first argument to be a MemberExpression"}

**Comment by StefH** [comment]
This should work. Do you have the latest version?

See
https://github.com/StefH/System.Linq.Dynamic.Core/blob/ea887692d003139961c313a1b723a6799a5e8979/test/System.Linq.Dynamic.Core.Tests/ExpressionTests.cs#L1395

**Comment by Franki1986** [comment]
I have updated to the latest nuget version.. should I use a myget version?

**Comment by Franki1986** [comment]
Maybe it is because I am using the DynamicParser?

**Comment by StefH** [comment]
DynamicParsers uses same code.

In my test, I use `.Name`
https://github.com/StefH/System.Linq.Dynamic.Core/blob/ea887692d003139961c313a1b723a6799a5e8979/test/System.Linq.Dynamic.Core.Tests/ExpressionTests.cs#L1401

Maybe this only works like this.

Else, can you open a new issue with an complete C# example?

**Comment by Franki1986** [comment]
What is striking, is that I am not using code inside a select or a where clause. I am only using an expression based on an object :
Here my test code. If you want I will create a new issue, maybe I am missing something and we will see it here:

```
public class TestClass{
    public List<string> MyList {get; set;}
}
```

```
var dataSource = new TestClass();
// Let MyList null...

var expressionText = "np(myList.FirstOrDefault())"
LambdaExpression e = DynamicExpressionParser.ParseLambda(ParsingConfig.Default, dataSource.GetType(),
               typeof(object), expressionText, null);
            var result = (e.Compile()).DynamicInvoke(dataSource);
```

**Comment by Franki1986** [comment]
Opened a new issue based on the information, I think it is because of the primitive list type. #366
